### ISSUE TITLE
Do I need jumpurl when I don't want to use statistics?

### ISSUE THREAD

**Issue by Boa2** [kartolo/direct_mail#100]
Hi all,
I recently upgraded a typo3 6.2 LTS installation to 7.6 LTS and installed jumpurl because of the direct_mail dependency. Since this update I get a lot of jumpurl errors.

When I don't want to count Link Responses, do I need jumpurl at all?

-Andrea

**Comment by kartolo** [comment]
no

**Comment by Boa2** [comment]
Thanks for the info.

**Comment by Boa2** [comment]
I can't deactivate jumpurl. Trying to do so causes a message: "Can't deactivate jumpurl because direct_mail depends on it".
-Andrea

**Comment by kartolo** [comment]
closing this. follow up in #103
