### ISSUE TITLE
processBounceMail does not process bounce mails

### ISSUE THREAD

**Issue by linkpool** [kartolo/direct_mail#102]
direct_mail 5.2.2
PHP 5.6.32
TYPO3 7.6.23
PHP IMAP 

I'm trying to debug the new processBounceMail feature.

I've sent a test newsletter to two non existing recipients and there are two response mails waiting in the pop3 account.

I took a look at:

AnalyzeBounceMail.php
private function processBounceMail($message)
		
        $attachmentArray = $message->getAttachments();
        if (is_array($attachmentArray)) {
         ....
         
But in our case $attachmentArray is empty

So I took a look at:
Fetch/Message.php

$this->attachments will be set by

protected function processStructure($structure, $partIdentifier = null)
 
In our case there won't be any $this->attachments added.

What works, ist that $this->plaintextMessage is set:

PLAIN::This is the mail system at host xxxxx. I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below. For further assistance, please send mail to postmaster. If you do so, please include this problem report. You can delete your own text from the attached returned message. The mail system : host mxlb.xxxx.de[80.67.xxx.xxx] said: 554 Sorry, no mailbox here by that name. (in reply to RCPT TO command)

But the plaintextMessage won't be analyzed later in the processBounceMail because attachmentArray is empty.

mhhh.

**Comment by linkpool** [comment]
Same issue as here:
https://github.com/kartolo/direct_mail/issues/72

**Comment by linkpool** [comment]
I've done some further debugging:

In our case the TYPO3MID is placed here

--3DD4151C4.1514976320/bst-u-web0.provider.net
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers
...
X-TYPO3MID: MID1749_t44690-16067261e1b8a251faa774722a143210

**message.php**
`
...
protected function processStructure
...

            //if (strtolower($structure->subtype) === 'plain' || ($structure->type == 1 && strtolower($structure->subtype) !== 'alternative')) {
            if ((strtolower($structure->subtype) === 'plain') || ($structure->type == 1 && strtolower($structure->subtype) !== 'alternative') || ($structure->type == 0 && strtolower($structure->subtype) == 'rfc822-headers')) {
`

**AnalyzeBounceMail.php**

...
processBounceMail
...

`
        // get attachment
        $attachmentArray = $message->getAttachments();
        $midArray = array();
        if (is_array($attachmentArray)) {
            foreach ($attachmentArray as $v => $attachment) {
                $bouncedMail = $attachment->getData();
                // Find mail id
                $midArray = $readMail->find_XTypo3MID($bouncedMail);
                if (is_array($midArray)) {
                    // if mid, rid and rtbl are found, then continue
                    break;
                }
            }
            
    	// search in MessageBody (see rfc822-headers as Attachments placed )
        }else{
        	$midArray = $readMail->find_XTypo3MID($message->getMessageBody());
		}

`

**Comment by linkpool** [comment]
[Desktop.zip](https://github.com/kartolo/direct_mail/files/1600389/Desktop.zip)

**Comment by pixelbrackets** [comment]
I tested the above Patch and was able to fetch bounce mails with it. I pasted the given code into a commit and created a PR (see #109), maybe more people could test this?

**Comment by linkpool** [comment]
Another change for:
Classes/Scheduler/AnalyzeBounceMail.php
Must be checked for "midArray['rid']" before the exec_SELECTquery
Otherwise the Scheduler-Task will never fnish in some circumstances.

        // Extract text content
        $cp = $readMail->analyseReturnError($message->getMessageBody());
++	if(isset($midArray['rid'])){
        $res = $this->getDatabaseConnection()->exec_SELECTquery(
...
....

[AnalyzeBounceMail.zip](https://github.com/kartolo/direct_mail/files/1747575/AnalyzeBounceMail.zip)
