### ISSUE TITLE
Debug line in production release

### ISSUE THREAD

**Issue by sgrossberndt** [kartolo/direct_mail#123]
The line

https://github.com/kartolo/direct_mail/blob/2632e1dc36ba784bcea9402ee6b0f4eb6ecfae7e/Classes/DirectMailUtility.php#L1227

is in a production release and triggers `open_basedir` errors if the PHP's temp directory has been configured not to be `/tmp`.

**Comment by xperseguers** [comment]
This has already been fixed (but not yet officially released I agree): a279da6

**Comment by kartolo** [comment]
closing this. fixed in develop branch, will be released with LTS compatibility
