### ISSUE TITLE
Version 5.2.2 contains bad debug code 

### ISSUE THREAD

**Issue by mediaessenz** [kartolo/direct_mail#128]
Line 1227 of the DirectMailUtility.php Class contains a bad debug piece:
```
file_put_contents('/tmp/dmail.php', var_export($htmlmail->theParts, true));
```
which throws a permission denied exception on my live system.
In the current master the whole line doesn't exists anymore.
So, please make a new release without this line.

**Comment by xperseguers** [comment]
This has already been fixed (but not yet officially released I agree): https://github.com/kartolo/direct_mail/commit/a279da6f6e4aebc81cd2075bac4d78e72ad32e73

**Comment by xperseguers** [comment]
And btw this ticket duplicates #123

**Comment by kartolo** [comment]
closing it. Thanks
