### ISSUE TITLE
Invoking mailer engine via cronjob fails w/Typo3 8

### ISSUE THREAD

**Issue by ut** [kartolo/direct_mail#130]
Invoking mailer engine via cronjob checks if the constant "TYPO3_cliMode" is true, otherwise the CLI script dies with the message "You cannot run this script directly!". Reason:  [The constant is removed with Typo3 8](https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.0/Breaking-72368-TYPO3ConstantsRemoved.html) (Thanks  @[julianhofmann](https://stichwort.org/typo3/typo3_climode-breaking-change-in-typo3-8-0/) for pointing to this)

Workaround for a Typo3 8 Installation: Change in cli/cli_direct_mail.php

```
if (!defined('TYPO3_cliMode')) {
    die('You cannot run this script directly!');
}

```
to 
```

if ((TYPO3_REQUESTTYPE & TYPO3_REQUESTTYPE_CLI) === 0) {
    die('You cannot run this script directly!');
}

```
A full fix would need to check the Typo3 version first and then use the appropiate check.

**Comment by kartolo** [comment]
I think I will remove the CLI functionality and refer to the scheduler task.

**Comment by ut** [comment]
I can understand your thought, the scheduler is a more Typo3-ish way, plus: why maintaining another approach? But personally, I would miss the possibility to manage this task from the command line. And since it just needs the change of just one line (for now), it might not be a big hazzle.
