### ISSUE TITLE
Add hook to post-process the list of distribution when starting to send

### ISSUE THREAD

**Issue by xperseguers** [kartolo/direct_mail#131]
When you use a 3rd-party extension like EXT:direct_mail_userfunc to create dynamic list of recipients, one of the use case I face is following:

- My dynamic list is related to participants to some event of mine
- The DM recipient list configuration looks like that:

![configuration](https://user-images.githubusercontent.com/646805/44844241-a0322b80-ac4a-11e8-89fd-e998b9080a87.png)

- So basically I want to target every person "participating" to some event
- Person may accept or decline the invitation, meaning the list evolves over time

Now I want to send a newsletter to the actual list of participants, like providing last minute details.

If I prepare my newsletter before the allowed last date for accepting registration, DM persists the list list of participants **at the point of time when I prepare my newsletter**, even if I schedule it for delivery 10 days afterwards.

The solution would be in that case to store, in addition to the actual list of recipients the configuration being used to generate that list. This may be done from within my business function called by EXT:direct_mail_userfunc and persisted for instance within the `$query_info` of DM, that's not a problem if I know what I'm doing.

The idea is that DM invokes an additional hook when it unserializes `$query_info` (from table `sys_dmail`) when **starting** to send the newsletter.

The hook should then:

- alter `$query_info` with the correct list of recipients (so that mailing can start correctly)
- remove additional "user" data from `$query_info` so that DM does not see any fancy internal parameters anymore
- persist the change to the DB so that if the newsletter is being sent, say to 500 participants and is sent by smaller chunks, the other chunks can be used on next run without invoking again the hook.

The hook should then get `$query_info` as reference (to be able to alter it) and the `$row` itself (could be useful), at the very least its uid so that changes may be persisted back to DB.

=> I will implement that, test that it works indeed as expected and propose an official patch for this repository if that's fine with you.

**Comment by jokumer** [comment]
Hello @xperseguers could you solve your behavior with the patch https://github.com/jokumer/direct_mail/commit/d631c5e501690333c824bb9db66bfc8709698aae from https://forge.typo3.org/issues/34432, when it comes to a TYPO3 v9.5 compatible version?

**Comment by xperseguers** [comment]
Hello @jokumer. NO, since the patch is about patching the specific scheduler task that creates a mail out of a draft. This is absolutely not my use case. In my use case I'm not preparing any draft. I'm preparing a newsletter which is marked to be sent at some specific time in the future. That future is usually "far" in the future, something like days or even possibly weeks. But the content of the newsletter is finalized. I really need just a hook (or signal of course, hook is a generic term) to let me do my stuff, I don't want nor expect DM to generally "refresh" the list because that's really what I need in some specific case but the general case should stay the same, that is you prepare a newsletter, choose who you want to send it too and target some future date to start the distribution. You don't expect DM to possibly change the list of recipients on its own.

**Comment by jokumer** [comment]
Thanks for clarifying. I will merge your hook then to the next version for TYPO3 v9.5
