### ISSUE TITLE
Migrating TYPO3_DB to doctrine

### ISSUE THREAD

**Issue by kartolo** [kartolo/direct_mail#133]
`$GLOBALS['TYPO3_DB']` must be migrated to doctrine.

See https://docs.typo3.org/typo3cms/CoreApiReference/8.7/ApiOverview/Database/Migration/Index.html

**Comment by kartolo** [comment]
I'm rewriting all DB queries and also deprecated API call. will take some time

**Comment by Nostrabramus** [comment]
Hello,
I just did a [pull request](https://github.com/kartolo/direct_mail/pull/145) to migrate to DBAL.

Regards

**Comment by Nostrabramus** [comment]
Hello, 
here you have another [commit](https://github.com/kartolo/direct_mail/pull/145/commits/9889b1437498ff81e8feb8ae989c5aae17818545) fot migrate to DBAL and other minor fixing

Regards

**Comment by masi** [comment]
Can I test or help in some other way to make the migration happen? How about other stuff that needs to be changed for v9?

**Comment by kartolo** [comment]
> yes,
> we were still working on the recipient list,
> the logic of some queries were not clear to us,
> if you're working on that part we stop here and test your code,
> thanks

Recipient list module is so far done. you can test it (and other module as well)

**Comment by masi** [comment]
This branch is currently only v8. Is there anything I could test or work on for v9?

**Comment by dni** [comment]
hi, any news on this?
