### ISSUE TITLE
Typo3 v9 compatibility

### ISSUE THREAD

**Issue by nollm** [kartolo/direct_mail#138]
It would be great to have compatibility with Typo3 v9. Are you planing to do this?

**Comment by kartolo** [comment]
need to check on jumpurl

**Comment by Nostrabramus** [comment]
Hello, 
are there any news on this issue?
we are trying to make it work on TYPO3 9 but it does not seem to me just a jumpurl problem: there are some core's changes to adapt to and all the queries use deprecated classes so they have to be moved to doctrine-dbal.
So I was wondering if we are working on an outdated version of Direct Mail, we are working on 5.2.2.

**Comment by kartolo** [comment]
see #133.

**Comment by masi** [comment]
jumpurl should be fairly easy to fix. Will do a fork and pull request next week.

**Comment by masi** [comment]
jumpurl has been patched, but there is no release yet. Have to use dev-master for now.

**Comment by mbechert** [comment]
Hey @kartolo  is there any update to TYPO3 9.5 in the future? Thanks !!!

**Comment by Gregor-Agnes** [comment]
Would be good to have information on this :) 
Will there be an update for 9.5? 
Is the anything I can do to support?

**Comment by msollmann** [comment]
Yeah, a version for 9.5 would be great! Or some information about this issue :-)

**Comment by derflocki** [comment]
Building on the work of @devmes I have added a minor fix to stop it from using pages_language_overlay: https://github.com/devmes/direct_mail/pull/1

**Comment by vmans** [comment]
Is there any info on this? I have one instance of direrct_mail semi-working now on 9LTS for a customer in production, but it's tricky I guess. Meanwhile I've made a subscription extension for 9LTS (https://github.com/vmans/vibis_ajaxmailsubscription) so let's move on.

**Comment by Gregor-Agnes** [comment]
Hi vmans
> Is there any info on this? I have one instance of direrct_mail semi-working now on 9LTS for a customer in production, but it's tricky I guess. Meanwhile I've made a subscription extension for 9LTS (https://github.com/vmans/vibis_ajaxmailsubscription) so let's move on.

Have a look in slack: https://typo3.slack.com/archives/C06PJG0PJ/p1550173187002200
Maybe you should talk to Jörg

**Comment by vmans** [comment]
> Hi vmans
> 
> > Is there any info on this? I have one instance of direrct_mail semi-working now on 9LTS for a customer in production, but it's tricky I guess. Meanwhile I've made a subscription extension for 9LTS (https://github.com/vmans/vibis_ajaxmailsubscription) so let's move on.
> 
> Have a look in slack: https://typo3.slack.com/archives/C06PJG0PJ/p1550173187002200
> Maybe you should talk to Jörg

Hi Gregor-Agnes,

All those different platforms... I have dropped a message in Slack, thanks for the suggestion.

**Comment by Nostrabramus** [comment]
Hello,
any news on direct_mail realease for TYPO3 v9?

I have another exception with TYPO3 9.5.6:

```
Doctrine\DBAL\Exception\TableNotFoundException

An exception occurred while executing 'SELECT `uid` FROM `pages_language_overlay` WHERE pid=1164 AND sys_language_uid=1': Table 'T387_Castagneto.pages_language_overlay' doesn't exist
```

**Comment by derflocki** [comment]
I have a "working" version running, however we are only using a small subset of the features: https://github.com/derflocki/direct_mail/tree/feature/github-133

If it works for you, good!

**Comment by Nostrabramus** [comment]
@derflocki tks, I will try it

**Comment by ziadabdulhai** [comment]
@derflocki, I have tried feature/github-133 but i receive an error on internal pages 
An error was encountered.
The HTML content could not be fetched.

**Comment by zolthan** [comment]
@kartolo any news about a release for typo3 9?

**Comment by CDRO** [comment]
@kartolo If you need any help on getting direct_mail running for TYPO3 9 please contact me, I've gathered some experience doing this while working on the crawler extension :-)

Any way, keep up the good work!

**Comment by kartolo** [comment]
I'm currently testing the current develop on my local setup.
tt_address is 9 LTS ready. [Jumpurl](https://github.com/FriendsOfTYPO3/jumpurl) should be 9 LTS compatible, but isn't uploaded to TER.

**Comment by FlorianWessels** [comment]
We have a version of this extension that allows you to configure Dmail records and create / send newsletters from internal pages using TYPO3 9. There are certainly still some bugs in the code, but this should be a good start... 

https://github.com/FlorianWessels/direct_mail/tree/TYPO3_9

**Comment by papillon6** [comment]
> Hello,
> any news on direct_mail realease for TYPO3 v9?
> 
> I have another exception with TYPO3 9.5.6:
> 
> ```
> Doctrine\DBAL\Exception\TableNotFoundException
> 
> An exception occurred while executing 'SELECT `uid` FROM `pages_language_overlay` WHERE pid=1164 AND sys_language_uid=1': Table 'T387_Castagneto.pages_language_overlay' doesn't exist
> ```

The table "pages_language_overlay" was removed in TYPO3 9. Can confirm the error. Creating this table (empty, structure only) seems to be a workaround for now...

We struggle with another error when mailer enginge is invoked manually or scheduler task is executed (sending the newsletter):

`The given alias 'fe_users' is not part of any FROM or JOIN clause table. The currently registered aliases are: sys_dmail_feuser_category_mm.`

Any ideas?

**Comment by noll1** [comment]
> 
> 
> I'm currently testing the current develop on my local setup.
> tt_address is 9 LTS ready. [Jumpurl](https://github.com/FriendsOfTYPO3/jumpurl) should be 9 LTS compatible, but isn't uploaded to TER.

JumpURL is official released for Typo3 v9.

**Comment by xmental** [comment]
> I'm currently testing the current develop on my local setup.
> tt_address is 9 LTS ready. [Jumpurl](https://github.com/FriendsOfTYPO3/jumpurl) should be 9 LTS compatible, but isn't uploaded to TER.

@kartolo Any news when direct_mail will be publish? Would be great!
[JumpURL](https://extensions.typo3.org/?L=0&id=1&tx_solr%5Bq%5D=jumpurl) is already released for TYPO3 9.

**Comment by jokumer** [comment]
Status update:
Last month @majernik added some improvements which got merged by @FlorianWessels into his TYPO3 v9 compatible branch here https://github.com/FlorianWessels/direct_mail/tree/TYPO3_9.
Some days ago @mh0rst improved rendering functions on a further fork of FlorianWessels.

Thanks to all contributers, who spend time to make this TYPO3 extension version 9.5 compatible. Your contribution helps to keep a great number of TYPO3 installations being up to date and running.

I checked out Florian Wessels branch TYPO3_9 and included the last change from Moritz Horstmann (mh0rst) and from others.
After some hours of additional bugfixes, improvements and documented cleanups I could execute all backend modules and scheduler tasks without errors. Creation and sending of internal- & external-pages, drafts and quick-mails was successful.

You are welcome to check out the latest state from https://github.com/jokumer/direct_mail/tree/TYPO3_9

**Comment by jokumer** [comment]
Status update:
Within help of Extension scanner by @lolli42 for TYPO3 version 9
I fixed for TYPO3 v9 compatibilty:
- Breaking changes at all
- Deprecations partially

Next task will be, to implement latest patches/PR`s, which @kartolo accepted and merged into current develop branch, and misses in TYPO3_9 branch.

**Comment by jokumer** [comment]
1. Yes, are in contact with DKD
2. Yes, already included. See https://github.com/jokumer/direct_mail/commit/98046ee2fb32d0ba6ff1120e1fe57e76877ab790
There is still a lot todo.
Any help appreciated :)

**Comment by chrcan** [comment]
> Status update:
> Last month @majernik added some improvements which got merged by @FlorianWessels into his TYPO3 v9 compatible branch here https://github.com/FlorianWessels/direct_mail/tree/TYPO3_9.
> Some days ago @mh0rst improved rendering functions on a further fork of FlorianWessels.
> 
> Thanks to all contributers, who spend time to make this TYPO3 extension version 9.5 compatible. Your contribution helps to keep a great number of TYPO3 installations being up to date and running.
> 
> I checked out Florian Wessels branch TYPO3_9 and included the last change from Moritz Horstmann (mh0rst) and from others.
> After some hours of additional bugfixes, improvements and documented cleanups I could execute all backend modules and scheduler tasks without errors. Creation and sending of internal- & external-pages, drafts and quick-mails was successful.
> 
Thank you for developing direct_mail!
I've installed the last version on a Typo 9.5.11 and get an error in the FE

(1/1) # 1294585866 InvalidArgumentException
No class named DirectMailTeam \ DirectMail \ Hooks \ JumpurlController

**Comment by jokumer** [comment]
@chrcan if you found an issue in version from https://github.com/jokumer/direct_mail/tree/TYPO3_9
please create a new issue or pull request in this repository.
I opened for creating issues.

**Comment by kevinlieser** [comment]
https://github.com/jokumer/direct_mail/tree/TYPO3_9 worked for me – thanks!

**Comment by jokumer** [comment]
Thx for feedback.

**Comment by chrcan** [comment]
https://github.com/jokumer/direct_mail/tree/TYPO3_9 worked for me – thanks so lot!
which extension do you use for the direct_mail newsletter subscription and unsubscription?
direct_mail_subscription is no longer maintained

**Comment by kevinlieser** [comment]
I made a fork at https://github.com/kevinlieser/direct_mail_subscription a few days ago. That worked for me.

**Comment by jokumer** [comment]
Using an over years adopted version of td_newsletter from Thomas Donner, Ancud IT-Beratung GmbH

**Comment by chris246** [comment]
@chrcan I use https://extensions.typo3.org/extension/fp_newsletter/ It also supports Captchas
