### ISSUE TITLE
Scheduler crashes when trying to add AnalyseBounceMail-task for the first time

### ISSUE THREAD

**Issue by David-Bascom** [kartolo/direct_mail#143]
**Reason:**

`Classes/Scheduler/AnalyzeBounceMailAdditionalFields.php` on line 66 and 67 calls method `$task->getService()` – but on first installation of the scheduler task `$task` is `NULL`.

**Possible solution:**
```
$service = $task ? $task->getService() : 'imap';	
$serviceHTML = '<select name="tx_scheduler[bounceService]" id="bounceService">' .
      '<option value="imap" ' . ($service === 'imap'? 'selected="selected"' : '') . '>IMAP</option>' .
      '<option value="pop3" ' . ($service === 'pop3'? 'selected="selected"' : '') . '>POP3</option>' .
```

**Comment by BastianBalthasarBux** [comment]
Works for me on TYPO3 v8.7.26

**Comment by BastianBalthasarBux** [comment]
Solution already in extension with Pull 145 https://github.com/kartolo/direct_mail/pull/145

Ticket can be closed IMHO

**Comment by typecat** [comment]
Can confirm both problem and solution for EXT:direct_mail 5.2.2 on TYPO3 7.6.32.

**Comment by kartolo** [comment]
I'm closing this. 

@typecat: does it still occurs if you remove the task and create new one?
