### ISSUE TITLE
JumpUrl links not working in current development-branch

### ISSUE THREAD

**Issue by mediaessenz** [kartolo/direct_mail#160]
The reason is a bug in the getRawRecord method of the JumpurlController.

The correct code (line 222-226) should look like this, because fetchAll() returns an array, also if only one record is found:
```
if ($row) {
                if (is_array($row[0])) {
                    return $row[0];
                }
            }
```

**Comment by kartolo** [comment]
@mediaessenz could you check #162. Thanks
