### ISSUE TITLE
Migrate documentation

### ISSUE THREAD

**Issue by kartolo** [kartolo/direct_mail#166]
See https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html

**Comment by jokumer** [comment]
On it..

**Comment by jokumer** [comment]
Someone may check, if an old webhook for documentation rendering is in play. Read more about here:
https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Webhook.html#webhook

**Comment by kartolo** [comment]
Thanks, I'll check it
