### ISSUE TITLE
direct_mail support for TYPO3 version 9 LTS (and in perspective 10 LTS)

### ISSUE THREAD

**Issue by cl-luka** [kartolo/direct_mail#171]
This is not an issue per se, but more of a question regardig the direct_mail support for the current and future TYPO3 LTS version.

According to https://extensions.typo3.org/extension/direct_mail/ the current version of direct_mail (5.2.2) only supports 7 and 8 LTS... 

Is there an new version (about to be released) which has support for 9 LTS?

**Comment by jokumer** [comment]
See issue #138

**Comment by cl-luka** [comment]
...oops - sorry!
