### ISSUE TITLE
error direct_mail FE & BE

### ISSUE THREAD

**Issue by chrcan** [kartolo/direct_mail#174]
With the new Version of direct_mail i have errors in Frontend and in the Backend Tools in Typo 9.5.11

Frontend Error:

(1/1) #1294585866 InvalidArgumentException
No class named DirectMailTeam\DirectMail\Hooks\JumpurlController

Backend Error:

(1/1) Error
Class 'DirectMailTeam\DirectMail\Module\Dmail' not found

(1/1) Error
Class 'DirectMailTeam\DirectMail\Module\RecipientList' not found

(1/1) Error
Class 'DirectMailTeam\DirectMail\Module\Statistics' not found

1/1) Error
Class 'DirectMailTeam\DirectMail\Module\MailerEngine' not found

(1/1) Error
Class 'DirectMailTeam\DirectMail\Module\Configuration' not found

**Comment by jokumer** [comment]
IMHO this repo do not have any TYPO3 v9.5 compatible version.
What is `the new Version of direct_mail`? Which version number does it has, which branch do you use?

**Comment by chrcan** [comment]
direct_mail 6.0.0-dev

**Comment by jokumer** [comment]
Thx for testing @chrcan 
Please report your issue in these repo, where you get the failed version from.
For example here https://github.com/jokumer/direct_mail/issues
Otherwise nobody can reproduce your reported behaviour.

**Comment by jokumer** [comment]
Issue moved to https://github.com/jokumer/direct_mail/issues/2
Please close.
