### ISSUE TITLE
No Jumpurls for https links in plaintext emails

### ISSUE THREAD

**Issue by virtuaris** [kartolo/direct_mail#178]
Is there a reason for method `substHTTPurlsInPlainText()` in `direct_mail/Classes/Dmailer.php` not respecting `https` URLs? 

Doing so disables the rendering of "JumpURLs" for these URLs which in turn disables "click statistics".

Our page is available via https only as are many other sites out there nowadays.  Thus this behaviour is at least an annoyance since one has to use `http` throughout all plaintext templates.

Cheers

Harald

**Comment by kartolo** [comment]
you're right. it really an ancient piece of code. any idea how to rewrite this part?

**Comment by virtuaris** [comment]
How about that?
```
if (!$this->jumperURL_prefix) {
     return $content;
}
$jumpUrlCounter = 1;
return preg_replace_callback(
     '/http[s]?:\/\/\S+/',
     function ($urlMatches) use (&$jumpUrlCounter) {
          $url = $urlMatches[0];
          if (strpos($url, '&no_jumpurl=1') !== false) {
               // A link parameter "&no_jumpurl=1" allows to disable jumpurl for plain text links
               $url = str_replace('&no_jumpurl=1', '', $url);
           } elseif ($this->jumperURL_useId) {
               $this->theParts['plain']['link_ids'][$jumpUrlCounter] = $url;
               $url = $this->jumperURL_prefix . '-' . $jumpUrlCounter;
           } else {
               $url = $this->jumperURL_prefix . str_replace('%2F', '/', rawurlencode($url));
           }
               $jumpUrlCounter++;
                return $url;
     },
     $content
);
```

**Comment by kartolo** [comment]
please verify and I'll merge this

**Comment by virtuaris** [comment]
Hi @kartolo,
we're currently testing the new code in production. I'll give you feedback when we're done.
