### ISSUE TITLE
Editor gets recipient list size 0, no mails sent (5.2.4)

### ISSUE THREAD

**Issue by ajindra** [kartolo/direct_mail#189]
When an editor chooses a recipient list of type "custom query" the list's size is given 0. When sending the newsletter no email is sent. The editor has ACL permissions set to see direct mail recipients, tt_address and the fields of the table for the custom query.
The editor sees recipients in lists of type "normal".
As admin you see all recipients and can send the newsletter to all of them.
This bug was introduced with version 5.2.4.

**Comment by ajindra** [comment]
Addition:
If the editor gets access permission to the page with is_siteroot=1 he/she can see the recipients.

**Comment by kartolo** [comment]
does the editor has access to the sysfolder, where the addresses are saved?
how does the query look like? release 5.2.4 adds access check for the custom query, only pages to which the BE user has access to, will be added in the query.

**Comment by ajindra** [comment]
Thanks for the fast response. Your guess was right: if the editor sees the sysfolder he can see the recipients in the direct mail module. Thanks for your help, you can close the issue.

Custom query is:
`SELECT uid,pid,deleted FROM sys_dmail_ttaddress_recipients WHERE ( newsletter = '17') AND sys_dmail_ttaddress_recipients.deleted=0`

and sys_dmail_ttaddress_recipients is a database view on
`CREATE VIEW sys_dmail_ttaddress_recipients AS 
	SELECT a.*, d.uid_foreign AS newsletter
	FROM tt_address a 
		RIGHT JOIN sys_dmail_ttaddress_category_mm d ON d.uid_local = a.uid
	WHERE a.email <> '' and d.uid_foreign <> '';`

**Comment by jokumer** [comment]
One of last the security fix did break behaviour for recipient handling.
See my comment in https://github.com/kartolo/direct_mail/commit/e675de9

**Comment by ajindra** [comment]
Side effect is: the editor can now see/export all 25000 email adresses in the sysfolder, not only the 900 in his recipient list.
