### ISSUE TITLE
TYPO3 10 LTS compatibility

### ISSUE THREAD

**Issue by fishgit** [kartolo/direct_mail#190]
Hi!

Are there any plans (or maybe even a time frame) about making direct_mail compatible to TYPO3 10 LTS?

Best regards,
Lars

**Comment by jokumer** [comment]
Yes there are plans, but small resources. See https://github.com/AnatoliZich/direct_mail/tree/typo3-10 or https://github.com/jokumer/direct_mail/tree/TYPO3_10
You may help to make it TYPO3 v10 compatible.

**Comment by matin73** [comment]
@jokumer : are there the latest securty patches added in version for TYPO3 9.5 and TYPO3 10 in your version under https://github.com/jokumer/direct_mail/tree/TYPO3_9 and https://github.com/jokumer/direct_mail/tree/TYPO3_10?

**Comment by jokumer** [comment]
@matin73 yes, but I did for TYPO3 v9.5 only. See

- https://github.com/jokumer/direct_mail/commit/844749c9e144c58192b4eb359b5cc1b7b39df793
- https://github.com/jokumer/direct_mail/commit/0e333a9cf699443928e1879f0e39d570b7d799a6
- https://github.com/jokumer/direct_mail/commit/7bd461701f11be568de1795cfe15293808487e1c

Commit "[Security] respect user restriction on query generator" introduces a regression, why I did not implement this. Also this fix, uses deprecated core methods, which has been obsolete, the day, this fix was published.
https://github.com/kartolo/direct_mail/commit/e675de9

Anatoli Zich merged Security fixes in his TYPO3 v10.4 branch. https://github.com/AnatoliZich/direct_mail/tree/typo3-10

**Comment by arnekolja** [comment]
Are the issues clear yet for 10 LTS?

**Comment by AnatoliZich** [comment]
see **https://github.com/kartolo/direct_mail/pull/199**

**Comment by ktallafus** [comment]
Hi!
Any news or time frame regarding the update?
Best regards, Kai

**Comment by kartolo** [comment]
@AnatoliZich PR #199 is merged to develop. Please test. I'll release it as Version 7.0.0 since it's 10 LTS only.

**Comment by webian** [comment]
Make direct_mail for TYPO3 10 LTS to use [FluidEmail](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Mail/Index.html#send-email-with-fluidemail) could be really useful:

- advantages of Fluid
- common template/config for all the website mails (fe user registration; login related; newsletter)

**Comment by bernd-reindl** [comment]
\DirectMailTeam\DirectMail\SelectCategories and \DirectMailTeam\DirectMail\Module\BaseScriptClass contains code which joins static_languages table to get sys_language.uid by static_languages.lg_typo3. But sys_language.static_lang_isocode has been removed in tt_address 5.2.0.
So this code leads in an exception.

**Comment by jokumer** [comment]
How can i reproduce this?

**Comment by bernd-reindl** [comment]
> How can i reproduce this?

Sorry. The field has been removed in static_info_tables. Not tt_address.

TYPO3 v10.4.9
static_info_tables 6.9.0
direct_mail 7.0.0-dev

Login to Backend.
Go to module Direct Mail / Configuration

important: Check if sys_language.static_lang_isocode is removed by "Database Analyzer".

**Comment by jokumer** [comment]
Confirmed

**Comment by kartolo** [comment]
> \DirectMailTeam\DirectMail\SelectCategories and \DirectMailTeam\DirectMail\Module\BaseScriptClass contains code which joins static_languages table to get sys_language.uid by static_languages.lg_typo3. But sys_language.static_lang_isocode has been removed in tt_address 5.2.0.
> So this code leads in an exception.

I create a new issue #215 for this. I'll close this issue.
If any incompatibility found, please create new Issue.

Thanks.
