### ISSUE TITLE
Wrong jumpurl prefix?

### ISSUE THREAD

**Issue by webian** [kartolo/direct_mail#192]
Hello, this installation has TYPO3 9 LTS + develop branch of direct_mail.

The sent newsletters have urls like http://domain.ext/path/of/newsletter/&mid=100025&rid=t_1&aC=3b977d68&jumpurl=2 that don't work because direct_mail adds `&mid` that in this use case should be `?mid`.

direct_mail adds the jumpurl prefix here:
https://github.com/kartolo/direct_mail/blob/61a78c1ad491a9fb56c5c4f4fdc2d0096d2cecef/Classes/DirectMailUtility.php#L1263

Old TYPO3 8 LTS version of this installation generated not speaking url (realurl disabled for newsletter pages) like http://domain.ext/index.php?id=123&mid=100025&rid=t_1&aC=3b977d68&jumpurl=2 so the `&mid` worked.

**Comment by kartolo** [comment]
it's fixed in develop branch. please check develop branch. thx
