### ISSUE TITLE
Plain text rendering not working

### ISSUE THREAD

**Issue by claude27** [kartolo/direct_mail#197]
Since I upgraded TYPO3 to 9.5 and direct_mail to its newest version 6.0.0, instead of the plain text the complete html source code of the html version (incl. html header) is showing up in the plain text view in the mail client (e.g. Thunderbird). 

The preview of a newsletter page in the browser, e.g. domain.xy/newlettertitle?type=99 however works as expected.

What could be the reason? Is it a bug or could it be a misconfiguration, caused by an old custom (e.g. typoscript) configuration?
Thanks for your help.

**Comment by kartolo** [comment]
Please check your access log, which URL is called. I can only assumed that a wrong URL is generated. (page type parameter is wrong appended). how is the URL generation in Site configuration?

**Comment by claude27** [comment]
Thank you for the tip with the access log. The links for the plain text version were listed as "GET /page-title-example/?type=99 HTTP/1.1". 
I added a PageTypeSuffix plain.txt: 99 in the site configuration and now the plain text version works as expected.

**Comment by claude27** [comment]
site configuration should have a PageTypeSuffix, e.g.
routeEnhancers:
   PageTypeSuffix:
     ...
     map:
     ...
       plain.txt: 99
