### ISSUE TITLE
Installation of friendsoftypo3/rdct mandatory?

### ISSUE THREAD

**Issue by seirerman** [kartolo/direct_mail#207]
I don't use the functionality of RDCT, yet the outdated version 1.0 gets installed with direct_mail.

Could this extension be moved from the "required" section to "suggest" in composer.json?

**Comment by kartolo** [comment]
If it's moved to suggest section, then we have to implement some check, the corresponding settings in configuration module are available if rdct extension is installed. 

would you create a PR? or sponsor this?

**Comment by seirerman** [comment]
I was just curious. No need to change anything, the extension works fine as it is. Closing this...
