### ISSUE TITLE
 Sending QuickMail - Column 'long_link_rdct_url' cannot be null

### ISSUE THREAD

**Issue by SSFGizmo** [kartolo/direct_mail#208]
If I try to create a Quickmail newsletter.  I get this Error:

An exception occurred while executing 'UPDATE `sys_dmail` SET `issent` = ?, `charset` = ?, `mailContent` = ?, `renderedSize` = ?, `long_link_rdct_url` = ? WHERE `uid` = 243' with params [0, "utf-8", "XXXXXX", 260, null]: Column 'long_link_rdct_url' cannot be null

direct_mail/Classes/Module/Dmail.php
```
 ->set('long_link_rdct_url', $this->urlbase)
 ->execute();
```

EXT:direct_mail version 6.0.1 (TYPO3 version 9.5.21).

**Comment by kartolo** [comment]
@SSFGizmo please check #209

**Comment by SSFGizmo** [comment]
Thank you, it works!

**Comment by kartolo** [comment]
6.0.2 will be released shortly
