### ISSUE TITLE
HTML Tag is shown in success message when sending a testmail

### ISSUE THREAD

**Issue by mkringel** [kartolo/direct_mail#212]
When I'm sending a newsletter for testing purpose in step 4 via the headline 'Individuelle Testmail' there is a html tag in the success message:

`Die E-Mail wurde an <strong>Testadresse <test@testprovider.de></strong> verschickt.`

Is there any chance to get rid of this html-tag? I've attached a screenshot below. 

Thanks in advance.

![Test](https://user-images.githubusercontent.com/71818670/94131143-d9571d00-fe5d-11ea-99ea-1655d8fffe0d.png)

**Comment by kartolo** [comment]
which version do you use?

**Comment by mkringel** [comment]
> which version do you use?

I'm using directmail 6.0.2 with Typo3 9.5.22.

**Comment by kartolo** [comment]
The flash message doesn't allow HTML Tag to be used. In locallang is removed the strong html tag. See [this commit](https://github.com/kartolo/direct_mail/commit/16ce7fc79d4d373a54c27408877d127c0ebce425#diff-c19c5e9559022c145b30e92225eca04d4efbabec66225d2de73effbb42df908e)

I change the line also on [translation server](https://translation.typo3.org/de/TYPO3.ext.direct_mail/translate/Resources/Private/Language/locallang_mod2-6.xlf#unit=3929537)

please reload your translation.
