### ISSUE TITLE
static_lang_isocode has been removed in static_info_tables 6.9.0

### ISSUE THREAD

**Issue by kartolo** [kartolo/direct_mail#215]
\DirectMailTeam\DirectMail\SelectCategories and \DirectMailTeam\DirectMail\Module\BaseScriptClass contains code which joins static_languages table to get sys_language.uid by static_languages.lg_typo3. But sys_language.static_lang_isocode has been removed in tt_address 5.2.0.
So this code leads in an exception.

_Originally posted by @bernd-reindl in https://github.com/kartolo/direct_mail/issue_comments/708207797_

**Comment by kartolo** [comment]
https://github.com/kartolo/direct_mail/issues/190#issuecomment-708242466

> > How can i reproduce this?
> 
> Sorry. The field has been removed in static_info_tables. Not tt_address.
> 
> TYPO3 v10.4.9
> static_info_tables 6.9.0
> direct_mail 7.0.0-dev
> 
> Login to Backend.
> Go to module Direct Mail / Configuration
> 
> important: Check if sys_language.static_lang_isocode is removed by "Database Analyzer".

**Comment by kartolo** [comment]
@bernd-reindl @jokumer: please check :)

**Comment by bernd-reindl** [comment]
@kartolo it works.

**Comment by kartolo** [comment]
thanks for checking
