### ISSUE TITLE
Invoke Mailer Engine

### ISSUE THREAD

**Issue by chrcan** [kartolo/direct_mail#219]
Hello,
I installed the direct-mail: dev-develop (https://packagist.org/packages/directmailteam/direct-mail) on a TYPO3 10.4.9.
When I run the Invoke Mailer Engine I get one:
	
Oops, an error occurred!
Argument 1 passed to Symfony\Component\Mime\Message::setBody() must be an instance of Symfony\Component\Mime\Part\AbstractPart or null, string given, called in /html/TYPO10/Franz/public/typo3conf/ext/direct_mail/Classes/Dmailer.php on line 688

**Comment by kartolo** [comment]
this is fixed in #220 (see bc2737a03ad1ffdc06aff2e0cebd1765cd34007e)
Thanks to @tobenschmidt
