### ISSUE TITLE
Exception in statistics module

### ISSUE THREAD

**Issue by lochmueller** [kartolo/direct_mail#224]
If there are no direct_mail objects and the user hit `Recalulcat data from cache` in the statistics BE module a exception is thrown:
```
Oops, an error occurred!
Argument 1 passed to DirectMailTeam\DirectMail\Module\Statistics::storeRecRec() must be of the type array, string given, called in /.../httpdocs/typo3conf/ext/direct_mail/Classes/Module/Statistics.php on line 1630
```

Thank you for the great extension.

**Comment by kartolo** [comment]
which version?

how could you see the `Recalulcat data from cache` link if there's no direct_mail object/newsletter? If you see the `Recalulcat data from cache`, it means you can see and choose the newsletter, which is already sent.

**Comment by lochmueller** [comment]
Good point. The issue was reported by a customer. Perhaps he open the stats and drop the direct_mail object in a second tab. Version is 5.2.4. Sorry... I don't have more information.
