### ISSUE TITLE
$jumpUrl is empty when 0

### ISSUE THREAD

**Issue by develth** [kartolo/direct_mail#227]
Hi,

the first link via jumpUrl always got an error, because of ID 0 and the empty check:

https://github.com/kartolo/direct_mail/blob/0c671b0206757c7f4930854ad5b86bfebf0bd04c/Classes/Middleware/JumpurlController.php#L105

Maybe a `if (empty($jumpurl) && $jumpurl !== 0) {`could fix this for the moment.

**Comment by gtitze** [comment]
@develth, I just had a look at the code. In my opinion, the error seems to be introduced a few lines earlier:
https://github.com/kartolo/direct_mail/blob/0c671b0206757c7f4930854ad5b86bfebf0bd04c/Classes/Middleware/JumpurlController.php#L95-L100

The target url generated from the jumpurl id is written to `$targetUrl`, but only written back to `$jumpurl` if there is a recipient record, i.e. the user did not use the sign-off link before. Thus, as far as i understand the code, your error should only occur with users who can't be loaded. Can you confirm this?

This behaviour differs from version 6.0.2 (cp. where the target url was returned to the client in any case:
https://github.com/kartolo/direct_mail/blob/fb06570048236a5bec356c1d37fa5148ccd99dfc/Classes/Hooks/JumpurlController.php#L77-L88

I suggest to restore the original behaviour by replacing the two occurrences of `$targetUrl` with `$jumpurl`. @kartolo @jokumer or is there any reason for this change which i oversee?

**Comment by jokumer** [comment]
Hello Greg, can you provide a patch?
As fa as I know, Ivan don't use direct_mail itself, and i have no projects, where jumpurl is used.

**Comment by jokumer** [comment]
@kanow verified this PR
