### ISSUE TITLE
var_dump in direct_mail/Classes/Hooks/JumpurlController.php

### ISSUE THREAD

**Issue by SSFGizmo** [kartolo/direct_mail#231]
direct_mail/Classes/Hooks/JumpurlController.php
```
throw new \Exception('authCode: Calculated authCode did not match the submitted authCode. varDump = '.var_dump($recipRow).' $recipientUid = '.$recipientUid.' theTable = '.$theTable.' authcode_fieldList'.$row['authcode_fieldList'].' AC = '. $aC .' AuthCode = '. $authCode, 1376899631);
```
URL in newsletter ?mid=xxx&rid=t_2&aC=xxx&jumpurl=xxx
If you change 2 to another number, you can see another record.

EXT:direct_mail version 6.0.2 (TYPO3 version 9.5.23, PHP 7.3).

**Comment by kartolo** [comment]
I closes this issue. PR #232 resolves this or is back port needed?

**Comment by gtitze** [comment]
@kartolo, from checking the code, this should not resolve the issue in my opinion since JumurlController was completely rewritten since version 6.0.2 and my #232 only fixes the rewritten version on the develop branch.

**Comment by gtitze** [comment]
@SSFGizmo, does PR #233 fix your issue?

From my opition, Typo3 should be configured in any case to not disclose messages of exceptions and errors to the user in production environment (information disclosure). More information on the settings can be found in [https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/Security/GuidelinesIntegrators/GlobalTypo3Options.html#displayerrors]

**Comment by SSFGizmo** [comment]
@gtitze, yes it did (https://github.com/kartolo/direct_mail/commit/875d8f57b951d596e462e4a3ef9cd76fad2bd6b0), thank you!
Maybe it was enough to remove var_dump from string.
I couldn't see the whole message, just output from var_dump.
