### ISSUE TITLE
with simulate_usergroup != 0  the content could not be fetched

### ISSUE THREAD

**Issue by ajindra** [kartolo/direct_mail#24]
If mod.web_modules.dmail.simulate_usergroup= is set, no content (plain or html) can be fetched. If the parameter is cleared, content fetching will work.

Page construct:
`+ Homepage`
`+-+ News`
`| +-+ News SysFolder`
`|`
`+-+ SysFolder Newsletter` , PageTSConfig with mod...dmail-settings
`| +-+ Newsletter Page` , Content elements with access settings (or unset)

On the Newsletter Page news records from the News Sysfolder are fetched and displayed. This works well for years.

Now I wanted to protect the Newsletter Page and set access rights to the frontend user group with uid 1. In the PageTSConfig of the SysFolder Newsletter I set mod.web_modules.dmail.simulate_usergroup=1.
This setting results in the error message that no html or plain text content could be fetched. 
I tried setting access restrictions to each content element on the Newsletter Page instead but it didn't work either.
It even doesn't work if no access restriction is set at all.

DirectMail version is 5.1.0, TYPO3 version is 7.6.10, PHP is 5.6.25

**Comment by kartolo** [comment]
direct_mail uses a hook to "interfere" the page rendering and set a FE-Group.

could you check in configuration module the value of  `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['determineId-PreProcessing']`

**Comment by ajindra** [comment]
the value is set as follows:

direct_mail = DirectMailTeam\DirectMail\Hooks\TypoScriptFrontendController->simulateUsergroup

**Comment by kartolo** [comment]
please try the fix in #27

**Comment by ajindra** [comment]
Now the error message has gone but it still doesn't work as expected: Upon creating a newsletter mailing, DirectMail doesn't get any contents, if the contents' access is restricted:

WARNUNG
The plain text content does not contain any direct mail boundaries.
The HTML content does not contain any direct mail boundaries.

**Comment by kartolo** [comment]
just tested it, it works for me.

- creates a new page in dmail sysfolder: 1 public content and 1 protected content
- preview in frontend => only public content is shown
- logged in using felogin, refreshed the newsletter page => both content is shown.
- in BE the page is fetched normally and newsletter is sent with both content.

Please check if you can preview the page after login.

The fix will be merged.
