### ISSUE TITLE
Column 'uid_foreign' in field list is ambiguous

### ISSUE THREAD

**Issue by typo3rel** [kartolo/direct_mail#240]
Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT `uid_foreign` FROM `sys_dmail_ttaddress_category_mm` `sys_dmail_ttaddress_category_mm` LEFT JOIN `tx_custom_domain_model_email` `tx_custom_domain_model_email` ON sys_dmail_ttaddress_category_mm.uid_local = tx_custom_domain_model_email.uid WHERE (`sys_dmail_ttaddress_category_mm`.`uid_local` = ?) AND (`tx_custom_domain_model_email`.`deleted` = 0)' with params [8750]: **_Column 'uid_foreign' in field list is ambiguous_**

version: 6.0.2
direct_mail/Classes/Dmailer.php line 476

`
    public function getListOfRecipentCategories(string $table, int $uid): string
    {
        if ($table === 'PLAINLIST') {
            return '';
        }

        $relationTable = $GLOBALS['TCA'][$table]['columns']['module_sys_dmail_category']['config']['MM'];

        $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable($table);
        $queryBuilder->getRestrictions()->removeAll()->add(GeneralUtility::makeInstance(DeletedRestriction::class));
        $statement = $queryBuilder
            ->select($relationTable.'.uid_foreign') // <----------------------------------------- modified 
            ->from($relationTable, $relationTable)
            ->leftJoin($relationTable, $table, $table, $relationTable . '.uid_local = ' . $table . '.uid')
            ->where($queryBuilder->expr()->eq($relationTable . '.uid_local', $queryBuilder->createNamedParameter($uid, \PDO::PARAM_INT)))
            ->execute();

        $list = '';
        while ($row = $statement->fetch()) {
            $list .= $row['uid_foreign'] . ',';
        }

        return rtrim($list, ',');
    }
`

**Comment by kartolo** [comment]
please check #246

And in what case does this error occur?
Thanks

**Comment by typo3rel** [comment]
Hi thanks for fixing this..
I have a List from a custom table and there is also a field uid_foreign
