### ISSUE TITLE
retrieveFileFolderObject() on null when uploading CSV

### ISSUE THREAD

**Issue by jipido** [kartolo/direct_mail#243]
After choosing TYPO3-folder, separtort,... when uploading a reciepent list, i got an retrieveFileFolderObject() on null error. 
Uploading CSV is not possible with any file. 

![schueleraustausch-portal-de-TYPO3-CMS-10-4-12- (9)](https://user-images.githubusercontent.com/314895/107481291-3ab62900-6b7e-11eb-9ede-6299e29fc35c.png)
![schueleraustausch-portal-de-TYPO3-CMS-10-4-12- (8)](https://user-images.githubusercontent.com/314895/107481279-37bb3880-6b7e-11eb-9612-4573e41f9c06.png)

**Comment by cnmarco** [comment]
Currently we also need the importer in our agency and have the same problem. I'll try to solve it and make the csv import work, if I get enough time.

**Comment by cnmarco** [comment]
My last commit to pull request #242 solved this issue in my test case. CSV import succeeded.
