### ISSUE TITLE
quickmail mode - mail sent without body

### ISSUE THREAD

**Issue by specialistaweb** [kartolo/direct_mail#247]
Hi Kartolo, thank you for your great work!

I have this configuration:

TYPO3 CMS V. 10.4.13
direct_mail v. 7.0.0
JumpURl v. 8.0.0
PHP Version 7.2.34-18+0~20210223.60+debian9~1.gbpb21322

I always use the QUICKMAIL mode to send the email; just filled correctly the fields I go ahead
all is fine but when I do a test email, the message is sent but the body received is EMTPY

The same occurs if I complete the process and the email is scheduled (or via Invoke the engine manually). All emails are sent but no body (text) is sent.

Hope you can solve as soon... thank you

**Comment by kartolo** [comment]
can't reproduce this. But I see that somehow direct_mail sent the quickmail with empty HTML part. Please check if your client prioritize to show HTML-Part instead text part

**Comment by kartolo** [comment]
please check #252.

**Comment by gilas1959** [comment]
hi eventually I can send you the parameters of my configuration. I changed some of them but without success.
The previous version (running under typo3 v.9.5) was fine and when I updated direct_mail to the latest version (compatible with TYPO3 v. 10 and there running) present this problem.

**Comment by gilas1959** [comment]
> please check #252.

forgive me but I'm not an expert user of github; I can see in #252 hi I can't apply any bugfix because I have not write access
