### ISSUE TITLE
Return_path not working anymore

### ISSUE THREAD

**Issue by Patta** [kartolo/direct_mail#251]
With direct_mail 7.0.0 and TYPO3 10.4.13 the configured return_path is not working anymore and the from_email is used instead the specific email for return/bounce mails.

**Comment by wowaTYPO3** [comment]
I had the same problem in TYPO3 10.4.16 with directmail 7.0.0, changing the line in Classes/Dmailer.php solved the problem. Please merge this in master and publish the fixed version! ;)

**Comment by joeschi** [comment]
Just updated to direct_mail 7.0.1 with Typo3 10.4.32. I can't reproduce this change. In my opinion, this is a wrong setting and does not correspond to the standard (RFC 5322, 6854). Some email clients, e.g. Outlook, will then show "sent on behalf of [return-path-adress]". The return-path must continue to be the return-path and not the sender in the mail header.
