### ISSUE TITLE
Creating scheduled task "Direct Mail: Analyze bounce mail" fails

### ISSUE THREAD

**Issue by cdaecke** [kartolo/direct_mail#253]
First of all: Thanks a lot for sharing your extension!

Setting up the scheduled task `Direct Mail: Analyze bounce mail` fails for me with the following error:

>Oops, an error occurred!
>Call to protected method TYPO3\CMS\Scheduler\Controller\SchedulerModuleController::addMessage() from context 'DirectMailTeam\DirectMail\Scheduler\AnalyzeBounceMailAdditionalFields'

Error log:
>Mon, 12 Apr 2021 21:19:40 +0200 [CRITICAL] request="a193bb07ee726" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to protected method TYPO3\CMS\Scheduler\Controller\SchedulerModuleController::addMessage() from context 'DirectMailTeam\DirectMail\Scheduler\AnalyzeBounceMailAdditionalFields' | Error thrown in file .../htdocs/typo3conf/ext/direct_mail/Classes/Scheduler/AnalyzeBounceMailAdditionalFields.php in line 131. Requested URL: https://www.example.com/typo3/index.php?route=%2Fmodule%2Fsystem%2FtxschedulerM1&token=--AnonymizedToken--&CMD=add - {"TYPO3_MODE":"BE","exception":{}}

Am I missing a configuration somewhere?

TYPO3: 10.4.14 (non composer mode)
ext:direct_mail: 7.0.0
PHP: 7.4.16
PHP: IMAP c-Client Version: 2007f

**Comment by jokumer** [comment]
Reason is not your configuration. We forgot to fix a TYPO3 Core change, when we made direct_mail TYPO3 v9 and v10 compatible
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-84387-DeprecatedMethodAndPropertyInSchedulerModuleController.html

**Comment by kartolo** [comment]
please check #261

**Comment by cdaecke** [comment]
@kartolo Top, works perfectly fine!

Thanks a lot for all your work!
