### ISSUE TITLE
Error on importing recipient list from CSV

### ISSUE THREAD

**Issue by annaemde** [kartolo/direct_mail#254]
Hallo,

when trying to import a CSV file as recipient list I get an error saying 
$GLOBALS['BE_USER']->getDefaultUploadTemporaryFolder() is null (Importer.php). It looks like the actual reason is that 
$this->userTempFolder()  (line 519) does not return any value as this function is deprecated.

Actually this happens for editors only. I myself (admin) can import CSV files without any problem.
Typo3 9.5.26, direct_mail 6.0.2

Any hint what I could do? 

Regards
Anna

**Comment by tomashavner** [comment]
Hi,
You have to create a filemount for fileadmin/_temp_ and give the be-user/be-usergroup access to this.
kind regards
Tomas

**Comment by annaemde** [comment]
Hi Tomas,

thanks for your message. I tried it with "fileadmin/_temp_", "fileadmin/temp" and "fileadmin/temp_files". The user in question can upload files to all the directories, but the error is still the same.

Kind regards
Anna

**Comment by tomashavner** [comment]
Try to put 
options.defaultUploadFolder=/fileadmin/_temp_/
in tsconfig of the user/usergroup

**Comment by annaemde** [comment]
Hi Tomas,
that works fine!! Thank you very much!
Best regards
Anna
