### ISSUE TITLE
TYPO3 10 localized page

### ISSUE THREAD

**Issue by NatalieKH** [kartolo/direct_mail#255]
When trying to send a localized newsletter in TYPO3 10, the following error message appears:
```
(1/2) Doctrine\DBAL\Exception\TableNotFoundException.
An exception occurred while executing 'SELECT `title` FROM `pages_language_overlay` WHERE (`pid` = ?) AND (`sys_language_uid` = ?)' with params [404, 2]: Table 'db.pages_language_overlay' doesn't exist
```

I think the problem is in line 1084 DirectmailUtility.php:
`if (strpos(VersionNumberUtility::getNumericTypo3Version(), '9') === 0) {`
here it should read -> 10 instead of 9 or be additionally checked for 10.

Settings:
TYPO3: 10.4.14 (composer mode)
ext:direct_mail: 7.0.0
PHP: 7.4.13

**Comment by jokumer** [comment]
Thx for your hint. Already solved with https://github.com/kartolo/direct_mail/pull/237

**Comment by kartolo** [comment]
@jokumer is right. It's fixed in develop branch. will make a release shortly.

I'll close this.
