### ISSUE TITLE
Extension key

### ISSUE THREAD

**Issue by SSFGizmo** [kartolo/direct_mail#257]
"The TYPO3 extension package "directmailteam/direct-mail", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)"

Composer installation
EXT:direct_mail version 7.0.0 (TYPO3 version 10.4.15, PHP 7.3).

(1/1) #1365429656 BadFunctionCallException
TYPO3 Fatal Error: Extension key "" is NOT loaded!

**Comment by jokumer** [comment]
Thx for report. Can you provide a change, and edit the existing composer.json?
https://github.com/kartolo/direct_mail/edit/develop/composer.json

This will help the author

**Comment by SSFGizmo** [comment]
https://github.com/kartolo/direct_mail/pull/258
only for this composer notice, not for error!
