### ISSUE TITLE
Typo3 10.4 ext_emconf.php is not up to date

### ISSUE THREAD

**Issue by SSFGizmo** [kartolo/direct_mail#259]
https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/DeclarationFile/Index.html#declaration-file-ext-emconf-php

Maybe just replace?
```
//OLD
$EM_CONF['direct_mail'] = [

//NEW
$EM_CONF[$_EXTKEY] = [
```

https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ExtensionArchitecture/DeclarationFile/Index.html#deprecated-configuration

- shy
- dependencies
- conflicts
- priority
- loadOrder
- module
- uploadfolder
- createDirs
- modify_tables
- lockType
- CGLcompliance
- CGLcompliance_note
- suggests

https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/DeclarationFile/Index.html#deprecated-configuration

**Comment by jokumer** [comment]
Would you provide a change request by creating a pull request?
Edit https://github.com/kartolo/direct_mail/edit/develop/ext_emconf.php
