### ISSUE TITLE
Unable to parse URI

### ISSUE THREAD

**Issue by nollm** [kartolo/direct_mail#268]
I have configured the entry point in my site configuration like this:

![site_config_fail](https://user-images.githubusercontent.com/42864489/124274234-4c09cd00-db41-11eb-94cb-888d3aea97cb.png)

Now I want to create a newsletter and get this error message:

![exception](https://user-images.githubusercontent.com/42864489/124274323-68a60500-db41-11eb-9ff7-7c8ffb7b8268.png)

It works fine when I set the full URL in the entry point:

![site_config_ok](https://user-images.githubusercontent.com/42864489/124274396-7f4c5c00-db41-11eb-8a37-b420ac9f7392.png)

The wrong URL "http:///newsletter?type=99" is the result of function `\DirectMailTeam\DirectMail\DirectMailUtility::getFullUrlsForDirectMailRecord`

**Comment by jokumer** [comment]
I made this change once for compatibility with TYPO3v9.
EXT:direct_mail in old days, requires to have set sys_domains and page ts-config, to get current domain from.
If you don't set any domain in your site-config, which is allowed, then EXT:direct_mail does not know, where to fetch the content from.
See dokumentation at Github https://github.com/kartolo/direct_mail/blob/develop/Documentation/Upgrading/UpgradingToVersion600/Index.rst#breaking-changes

**Comment by nollm** [comment]
Okay, thanks for your help!
