### ISSUE TITLE
No Extensionkey in Release 7.0.0

### ISSUE THREAD

**Issue by dni** [kartolo/direct_mail#269]
The TYPO3 extension package "directmailteam/direct-mail", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

can you tag a release 7.0.1 with the extension key? its needed for Helhum\Typo3Console

**Comment by jokumer** [comment]
Extension key already added to composer.json (dev-branch). Should be available within next release.
https://github.com/kartolo/direct_mail/blob/develop/composer.json#L51

**Comment by dni** [comment]
nice, i saw it :) when is next release though :)?

**Comment by kartolo** [comment]
I'll release it today :)
