### ISSUE TITLE
Typo3 11 compatibility

### ISSUE THREAD

**Issue by christophrunkel** [kartolo/direct_mail#278]
I would sponsor a Typo3 11 compatibility. Please let me know if anyone has time and effort to do this or also sponsor this extension update.

**Comment by h3nn3s** [comment]
I propably would join forces. 
I recently had a discussion with a client on how to receive v11 compatibility and when - I is willing to co-sponsor parts of development.

**Comment by jokumer** [comment]
Does anyone checked current branch from @SSFGizmo https://github.com/SSFGizmo/direct_mail/tree/11.x
and want support it?

**Comment by h3nn3s** [comment]
Did not notice that fork, yet. Thanks for sharing.

**Comment by dmitryd** [comment]
@kartolo Are there any plans to release official version for v11? :)

**Comment by dmitryd** [comment]
More development in the fork: https://github.com/SSFGizmo/direct_mail/pull/9

**Comment by kartolo** [comment]
@SSFGizmo has done a real good job and his PR is merged to develop branch.
Please test the [alpha release](https://github.com/kartolo/direct_mail/releases/tag/v8.0.0-alpha) and report any issues found.
