### ISSUE TITLE
Sending mails CSA certified

### ISSUE THREAD

**Issue by is-fun** [kartolo/direct_mail#286]
Hi,

we offer CSA-certified SMTP servers for email marketing:
https://www.is-fun.de/en/newsletter-server/

We would like to know if you are insterested to cooperate with us and make direct_mail CSA-compatible?
It would help all of your customers who are CSA-members or who are using the SMTP-server of a CSA-member.
It is not very complicated. You need 3 header entries in each email and the one-click-unsubcribe functionality (RFC 8058). I am looking forward to assist you in these issues. 

Further information about CSA:
https://certified-senders.org/

Please let me know if this is of interest. 

Best Regards
Robin Fundinger
iS-Fun Internet Services GmbH

**Comment by kartolo** [comment]
this is only a plugin for the TYPO3 CMS. It uses the mail server configured in TYPO3 CMS.
