### ISSUE TITLE
HTML checkbox not set in csv import

### ISSUE THREAD

**Issue by kartolo** [kartolo/direct_mail#295]
in the csv importer HTML flag is not imported, even though this is set in the import wizard

release v8.0.0-alpha

**Comment by SSFGizmo** [comment]
Field 'Recieve e-mails as HTML' (DB tt_address.module_sys_dmail_html)

* https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Typo3CoreEngine/Database/Index.html
* https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.html

```
$dataHandler = GeneralUtility::makeInstance(DataHandler::class);
$dataHandler->stripslashes_values = 0;
//$dataHandler->enableLogging = 0;
$dataHandler->start($data, []);
$dataHandler->process_datamap();

if ($dataHandler->errorLog !== []) {
    $logsStr = '';
    foreach ($dataHandler->errorLog as $log) {
        $logsStr .= $log . PHP_EOL;
    }
    $message = $this->createFlashMessage($logsStr, 'Import errors', 2, false);
    $this->messageQueue->addMessage($message);
}`

```
https://github.com/SSFGizmo/direct_mail/commit/48240bfe40d2592b1987cc973b89b0f855c910da

> [1.1.12]: SQL error: 'Incorrect integer value: 'xx' for column `tt_address`.`module_sys_dmail_html` at row 1' (tt_address:NEW1)

**Comment by SSFGizmo** [comment]
Download with 'Raw values' and import seems to work

![raw_values](https://user-images.githubusercontent.com/36045938/192895408-7cb1871d-8d31-4d86-96e9-8b5d0d71a7a1.jpg)

**Comment by imminger** [comment]
Having the same issue. Normally we import only a list of email addresses (see test file). None of the imported recipients has module_sys_dmail_html set to 1 - even though the checkbox was activated during import

Tested with TYPO3 11.5.21 and DirectMail:11.x ([a284531](https://github.com/kartolo/direct_mail/commit/a284531ba25266b05f80c5980cde39f5a9343588))

### Test file
[test-import.csv](https://github.com/kartolo/direct_mail/files/10381691/test-import.csv)

### Import settings
![Bildschirmfoto 2023-01-10 um 11 35 26](https://user-images.githubusercontent.com/15834641/211529286-729e8a75-d908-4ba6-83cc-f5484ae9d649.png)

### Result
![Bildschirmfoto 2023-01-10 um 11 36 19](https://user-images.githubusercontent.com/15834641/211529259-5db5e856-f0e7-4092-8705-c6ce0b177d69.png)

**Comment by SSFGizmo** [comment]
@imminger Can you check new version? (9.0.1)

**Comment by imminger** [comment]
@SSFGizmo The new version fixes this issue for me. 

- If the checkbox is checked, module_sys_dmail_html is set to 1
- If the checkbox is not checked, module_sys_dmail_html is 0

Thank you very much for fixing this so quickly (and for updating DirectMail for TYPO3 11)

**Comment by SSFGizmo** [comment]
thanks for your feedback
