### ISSUE TITLE
remove or change php dependency in ext_emconf.php

### ISSUE THREAD

**Issue by mediaessenz** [kartolo/direct_mail#305]
Currently the TYPO 11 compatible development version contains this php dependency in the ext_emconf.php:
```php
 'php' => '7.4.0-8.0.99',
```
Since TYPO3 11 is compatible up to php 8.1 and the active support of php 8.0 ends in one month, this dependency should be removed or at least increased to 8.1.99.

Btw.: The composer.json does not contain a php version requirement.

**Comment by SSFGizmo** [comment]
Changed
