### ISSUE TITLE
Module icon in pagetree is gone

### ISSUE THREAD

**Issue by mediaessenz** [kartolo/direct_mail#306]
Since the change to Icons.php the pagetree icon is gone.
This module use the icon identifier "directmail-folder", which points to EXT:direct_mail/Resources/Public/Icons/ext_icon_dmail_folder.png
Unfortunately this image does not exists.
There is only a (ugly) gif with this name: ext_icon_dmail_folder.gif

**Comment by kartolo** [comment]
please check #319

**Comment by SSFGizmo** [comment]
Should be fixed already.
