### ISSUE TITLE
Undefined array key "firstname" in Middleware/JumpurlController.php line 371

### ISSUE THREAD

**Issue by mediaessenz** [kartolo/direct_mail#307]
Since not all fields defined in (default|add)RecipFields are always included in a recipient record (e.g. first name and phone), marker substitution should be more error-tolerant.

This easily can be done by changing this line from
```php
$this->recipientRecord[$substField],
```
to
```php
$this->recipientRecord[$substField] ?? '',
```

**Comment by SSFGizmo** [comment]
Should be fixed already
