### ISSUE TITLE
Error when trying to save the configuration (direct_mail 8.0.0-alpha on TYPO3 11)

### ISSUE THREAD

**Issue by ineswillenbrock** [kartolo/direct_mail#309]
TYPO3 11.5.17
direct_mail 8.0.0-alpha
PHP 7.4.30
User is Admin and has the rights for the install-tool.
Both direct_mail static templates are included.

Trying to save the global configuration with the "Configuration"-module on a sysfolder with the direct_mail plugin results in an error:

(1/1) TypeError

explode() expects parameter 2 to be string, null given
in /html/typo3/typo3conf/ext/direct_mail/Classes/Utility/TsUtility.php line 76

My fault?

**Comment by SSFGizmo** [comment]
* New Folder
*  Edit => Behaviour => Contains Plugin[module] => Direct Mail [dmail]
* DM  => Configuration => Update configuration

`explode() expects parameter 2 to be string, null given`

=> pages.TSconfig ist empty

**Comment by SSFGizmo** [comment]
@ineswillenbrock Would you please check with 11.x branch?

**Comment by ineswillenbrock** [comment]
@SSFGizmo the one-line-change works for me, thanks!
