### ISSUE TITLE
Detailed information not changeable in step 2

### ISSUE THREAD

**Issue by paul-keller** [kartolo/direct_mail#32]
Problem with TYPO3 7.6: When sending the Newsletter with the Direct Mail Wizzard it is not possible to change the properties in step 2 (detailed information). The flexform for the changes opens, but the changes aren't saved. 
Im someone would like to change the language Parameter (&L=1), this is not possible in step to. With earlier Versions, this has worked perfectly.
In TYPO3 7.6 before sending a newsletter in an other language, the parameter has to be changed in the direct mail configuration.

**Comment by SIlverback-Web** [comment]
Hi,
any news regarding this issue? It's very important for a current project of mine.

**Comment by peterkraume** [comment]
Well, this bug has been fixed in 455fcf58b732dfc9cc1eb1e2604b89f730b583ad almost one year ago!
I'd really appreciate a new tag and TER release!

**Comment by kartolo** [comment]
closing this. new version will be released soon. see #47
