### ISSUE TITLE
Change view in recipients list of tt_address to fields first_name and last_name

### ISSUE THREAD

**Issue by klodeckl** [kartolo/direct_mail#329]
Since tt_address 6.0 there is a breaking change, the field “name“ is not automatically filled with “first_name” and “last_name”. This leads to empty “name“ fields. In the module recipients list the “name“ field is displayed for every tt_address entry. This should be changed to “first_name“, “middle_name“ and “last_name“ (with spaces).
See
https://github.com/FriendsOfTYPO3/tt_address/blob/master/Documentation/Administration/Changelog/v/6-0-0.rst#handling-of-field-name

**Comment by SSFGizmo** [comment]
@klodeckl Who you create new "tt_address" records?

**Comment by klodeckl** [comment]
I fill in first name and last name (or subscription extension does it). Why?
