### ISSUE TITLE
jumpurl_tracking_privacy problem

### ISSUE THREAD

**Issue by zabinetta** [kartolo/direct_mail#363]
Hi, 
since I updated to TYPO3 11 and direct_mail 8.0.0, I get an error on my existing jumpurl links. The error is like:

> Argument 1 passed to DirectMailTeam\DirectMail\Middleware\JumpurlController::initRecipientRecord() must be of the type string, null given, called in /html/mytypo3installation/typo3conf/ext/direct_mail/Classes/Middleware/JumpurlController.php on line 99

url is like
> https://www.example.de/ausgabe-26-dezember-2022?mid=318&aC=cf3d2e87&jumpurl=2

I used jumpurl_tracking_privacy, so the rid-parameter is missing.
when I disable jumpurl_tracking_privacy, the rid parameter is sent and the links are working.
urls are then like:
> https://www.example.de/ausgabe-26-dezember-2022?mid=320&rid=t_2405&aC=550f56b0ef04309545938f868328fd8d6830e7e4&jumpurl=2

TYPO3 version: 11.5.21
direct_mail 8.0.0
PHP 7.4.33
jumpurl 8.0.3

has anybody had this, too?
with the best regards,
Sabine

**Comment by SSFGizmo** [comment]
@zabinetta Can you please check with the 11.x-branch, if this error still exists?

**Comment by zabinetta** [comment]
the error is gone. Thank you so much!
