### ISSUE TITLE
Number of opened mails strongly decreased after update from 6.0 to 11.x

### ISSUE THREAD

**Issue by imminger** [kartolo/direct_mail#379]
We updated from DirectMail 6.0.2 to the 11.x branch. 
After the update the number of opened mails has strongly decreased. They are now about a third or quarter of the old value.

I think this is because of how dmailerping.gif views are logged in sys_dmail_maillog. 

The aC parameter is used as recipient ID:
https://github.com/kartolo/direct_mail/blob/4666e34f0075fb454113606b3df1821121ef0e75/Classes/Middleware/JumpurlController.php#L126

The recipient ID is then casted to int:
https://github.com/kartolo/direct_mail/blob/4666e34f0075fb454113606b3df1821121ef0e75/Classes/Middleware/JumpurlController.php#L137

Could it be that casting the recipient ID (= auth code) does not work correctly (as described [here](https://github.com/kartolo/direct_mail/issues/290) - but I can't find the same error message)?  
In the 6.0.2 version there was no casting:

https://github.com/kartolo/direct_mail/blob/6.0/Classes/Hooks/JumpurlController.php#L186

When I open this link, I get to following sys_dmail_maillog entry
https://example.org/newsletter-32?mid=3911&rid=t_592484&aC=0456e3ea4522004f013b17215183ab16a0dabbab&jumpurl=https://example.org/typo3conf/ext/direct_mail/Resources/Public/Icons/dmailerping.gif

![Bildschirmfoto 2023-01-27 um 11 45 59](https://user-images.githubusercontent.com/15834641/215069157-64c2b3d2-a19d-4db4-84c0-0a284e24d606.png)

https://example.org/newsletter-vorlage?mid=4005&rid=t_688612&aC=d608890ffc09d2a10630433c6cb1020892cf4363&jumpurl=https://example.org/typo3conf/ext/direct_mail/Resources/Public/Icons/dmailerping.gif
… results in 
![Bildschirm­foto 2023-02-02 um 13 45 12](https://user-images.githubusercontent.com/15834641/216328885-f2a5167e-8298-4909-93d8-05bd3bf987b9.png)

Someone on Slack made the same observation:
https://typo3.slack.com/archives/C06PJG0PJ/p1635848915004200

**Comment by SSFGizmo** [comment]
Reminder

```
`OLD
GeneralUtility::stdAuthCode

NEW
GeneralUtility::hmac
```
* https://api.typo3.org/11.5/_general_utility_8php_source.html
`
```
'###SYS_AUTHCODE###'        => AuthCodeUtility::getHmac($recipientRow, $this->authCodeFieldList),

'&aC=###SYS_AUTHCODE###' .

$submittedAuthCode  = $this->request->getQueryParams()['aC'];

$recipientUid = $submittedAuthCode;

'rid'           => (int)($recipientUid ?? $this->recipientRecord['uid']),
```
