### ISSUE TITLE
perplexing statistics

### ISSUE THREAD

**Issue by adrian-cmd** [kartolo/direct_mail#38]
was wondering about the statistics:
why hast recipients total/sent another count than the "mails sent"?

![screenshot 2016-12-22 11 03 40](https://cloud.githubusercontent.com/assets/322735/21422149/b52d49c4-c836-11e6-973b-1d5822713840.png)

**Comment by fjacobi** [comment]
In most cases those don't have the module_sys_dmail_html flag.

**Comment by kartolo** [comment]
does @fjacobi answer your question. I'll reopen this, if you have another question
