### ISSUE TITLE
Email "" does not comply with addr-spec of RFC 2822.

### ISSUE THREAD

**Issue by quadronet** [kartolo/direct_mail#385]
I can't send an email, only this error is displayed when initiating the send.

PHP 8.15, TYPO3 11.5.24

**Comment by SSFGizmo** [comment]
@quadronet 
Check that each recipient has a correct email address.
Which dm-version you are using?
Error in which file?

**Comment by quadronet** [comment]
I use Version 8
    'version' => '8.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.0-11.99.99',
            'lowlevel' => '11.5.0-11.99.99',
            'tt_address' => '5.3.0-7.0.99',
            'php' => '7.4.0-8.0.99',
            'jumpurl' => '8.0.3-',
            'rdct' => '2.1.0'
        ],

Error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Email "" does not comply with addr-spec of RFC 2822. | Symfony\Component\Mime\Exception\RfcComplianceException thrown in file /var/www/vhosts/julaine.de/julaine.1qn.de/typo3_src-11.5.24/vendor/symfony/mime/Address.php in line 56. Requested URL: https://julaine.1qn.de/typo3/module/DirectMailNavFrame/MailerEngine?token=--AnonymizedToken--&id=36&invokeMailerEngine=1

**Comment by quadronet** [comment]
The problem is solved, the configuration of direct_mail was lost due to the TYPO3 update, so it didn't work.
