### ISSUE TITLE
Jumpurl links in mail end up in a 503

### ISSUE THREAD

**Issue by vmans** [kartolo/direct_mail#386]
Latest 11LTS
PHP8.0
latest direct_mail dev version

Small batches show no problems with the jumpurl but at larger scale clicking a link in a mail. This is one of the lines from the log:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: str_replace(): Argument #2 ($replace) must be of type array|string, int given | TypeError thrown in file .../web/public/typo3conf/ext/direct_mail/Classes/Middleware/JumpurlController.php in line 263. Requested URL: https://...?mid=1000&rid=t_20973&aC=449bbd880729ea571749521ebd857cfb82dc1d5b&jumpurl=3 `

**Comment by SSFGizmo** [comment]
@vmans 
dev-branch is not up to date, use 11.x instead.
