### ISSUE TITLE
v9.2: wrong display of selected draft in the "Direct Mail: Create Mail from Draft (direct_mail)" task dropdown

### ISSUE THREAD

**Issue by Patta** [kartolo/direct_mail#394]
ddev, composer
TYPO3 11.5.24
direct_mail 9.2.1

In backend module "scheduler", the selected draft in the "Direct Mail: Create Mail from Draft (direct_mail)" task dropdown "Choose Draft to create DirectMail from" is wrong and always the first draft from the selection. It seems that only the view is wrong. The selected draft is correct in the database tx_scheduler_task table record.

**Comment by SSFGizmo** [comment]
@Patta 
Would you please check with v9.2.2?

**Comment by Patta** [comment]
@SSFGizmo issue is resolved with v9.2.2. Thanks for your awesome work!
