### ISSUE TITLE
Absolute url of dmailerping.gif

### ISSUE THREAD

**Issue by webian** [kartolo/direct_mail#4]
Hi @kartolo,
I have a doubt on how to setup dmailerping.gif

Long story short, the resulting src of the dmailerping.gif of the received newsletter is
`http://example.com/index.php?id=74&rid=f_5&mid=19&aC=695171a3&jumpurl=http://example.com/typo3conf/ext/direct_mail/res/gfx/dmailerping.gif`

Debugging what happens when this url reaches my server I noticed that, in class JumpurlController and method preprocessRequest, the condition
`if (preg_match('#/dmailerping\\.(gif|png)$#', $checkPath) && GeneralUtility::isAllowedAbsPath($checkPath))`
is false cause here
`$checkPath = /var/www/example.com/htdocs/http://example.com/typo3conf/ext/direct_mail/res/gfx/dmailerping.gif`
that indeed is an invalid path on my server and specifically
`static::validPathStr($path) = false`

I add that at the end the newsletter is marked as viewed in the statistics but there's something that I don't understand about that check.

Am I doing something wrong?

**Comment by kartolo** [comment]
Hi,
the jumpurl link is not correct.
I use following simple TS to include the pixelbug:
<pre>
  20 = IMAGE
  20 {
    file = typo3conf/ext/direct_mail/res/gfx/dmailerping.gif
    params = dmailerping=1
  }
</pre>

you can use any path as image tracker. important is the parameter `dmailerping=1` as image parameter.

best regards,

Ivan
