### ISSUE TITLE
Jumpurl Problems in PHP8

### ISSUE THREAD

**Issue by zabinetta** [kartolo/direct_mail#408]
Hello,
there's a problem with jumpurl in PHP8, since I changed from PHP 7.4, the links in my existing newsletters will result in an error:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: str_replace(): Argument #2 ($replace) must be of type array|string, int given | TypeError thrown in file /myTypo3Folder/typo3conf/ext/direct_mail/Classes/Middleware/JumpurlController.php in line 263. Requested URL: https://www.mydomain.de/mynmewsletterpage?mid=326&rid=t_1218&aC=f62b761ca0691b2e3b8c120e97cc89dd696ae1cd&jumpurl=25 `
when I put PHP back to 7.4 , the jumpurl-links will be working again.

with the best regards,
Sabine

PHP 8.0 / 7.4
TYPO3 11.5.26
jumpurl 8.1.0
direct_mail 9.0.2

**Comment by SSFGizmo** [comment]
https://github.com/kartolo/direct_mail/issues/405?

**Comment by zabinetta** [comment]
right :)

**Comment by kartolo** [comment]
closing this, since it's solved.
