### ISSUE TITLE
Translated page title is not used for subject

### ISSUE THREAD

**Issue by Patta** [kartolo/direct_mail#414]
TYPO3 11.5.27
PHP 8.1.18
direct_mail 9.3.0

If you have an translated page to e.g. language uid 1, the page title of the translated page is not fetched/used for a new internal page mail in direct mailer module. It seems, that only the content is fetched.
Maybe a missing feature?

**Comment by svengruetzmann** [comment]
I can confirm this issue with these versions
TYPO3 11.5.35
PHP 7.4.33
direct_mail 9.5.2

**Comment by Patta** [comment]
resolved in [v12.x](https://github.com/kartolo/direct_mail/tree/12.x)
