### ISSUE TITLE
setup github actions typo3-upload-ter

### ISSUE THREAD

**Issue by kartolo** [kartolo/direct_mail#424]
https://github.com/tomasnorre/typo3-upload-ter needs to be setup to automatically upload the releases to TER

**Comment by miniton** [comment]
Is it possible to support this task?

**Comment by kartolo** [comment]
github action to release to ter on tagging is added. This will be tested, on next release :)

additionally I added some linter task (taken from [tea extension ](https://github.com/FriendsOfTYPO3/tea)). some of these are deactivated and will be activated and code will be refactored accordingly.
