### ISSUE TITLE
Adding attachment is not working

### ISSUE THREAD

**Issue by mediaessenz** [kartolo/direct_mail#44]

**Comment by peterkraume** [comment]
The problem with the missing attachment occours, when you create a new newsletter, e.g. from an internal page, then in step 2 edit the record and add the attachment. Upon saving a new direct_mail record without the attachment is created.

Workaround:
- create new newsletter
- go back to step one
- edit the freshly created record in "direct mail" section
- add attachment as usual
- proceed until step 5

**Comment by kartolo** [comment]
#32

**Comment by kartolo** [comment]
reported in #32

**Comment by peterkraume** [comment]
Well, this bug has been fixed in 455fcf58b732dfc9cc1eb1e2604b89f730b583ad almost one year ago!
I'd really appreciate a new tag and TER release!

**Comment by mediaessenz** [comment]
Not a bad idea ;-)

**Comment by kartolo** [comment]
closing this. new release coming soon. see #47
