### ISSUE TITLE
Error at the creation of a newsletter with categories

### ISSUE THREAD

**Issue by hloens** [kartolo/direct_mail#447]
TYPO3: 11.5.33
Direct Mail: 9.5.1
PHP: 7.4.33

If i generate a newsletter with categories, i get the error messsage:

`Call to undefined method TYPO3\CMS\Core\Database\Query\QueryBuilder::fetchAllAssociative()`

Solution. Add in the the file _EXT:direct_mail/Classes/Repository/SysDmailCategoryRepository.php_ on line 56:

`->executeQuery()`

**Comment by kartolo** [comment]
fixed in  https://github.com/kartolo/direct_mail/pull/452
