### ISSUE TITLE
Plaintext rendering vs. FAL images

### ISSUE THREAD

**Issue by JLNNN** [kartolo/direct_mail#45]
# Import from: https://forge.typo3.org/issues/62125

## Description:
Since TYPO3 Cms uses FAL for image rendering the "old" image rendering wont fit the plantext rendering methods.

Now there are links to images generated that look somewhat like that
> http://www.yourdomain.com/uploads/pics/1
http://www.yourdomain.com/uploads/pics/2
http://www.yourdomain.com/uploads/pics/3

My installation specs
I use 
- TYPO3 Cms 6.2.4
- directmail 4.0.0
- PHP 5.4.30

Quickfix by omitting images
My "quickfix" so far is to omit images completely.
That can be done by changing lines 89-99 in EXT:direct_mail/pi1/class.tx_directmail_pi1.php

```php
case 'textpic':
    $lines[] = $this->getHeader();
    // if (($CType == 'textpic') && !($this->cObj->data['imageorient']&24))    {
    //     $lines[] = $this->getImages();
        $lines[] = '';
    // }
    $lines[] = $this->breakContent(strip_tags($this->parseBody($this->cObj->data['bodytext'])));
    // if (($CType == 'textpic') && ($this->cObj->data['imageorient']&24))    {
    //     $lines[] = '';
    //     $lines[] = $this->getImages();
    // }
break;
case 'image':
    $lines[] = $this->getHeader();
    // $lines[] = $this->getImages();
break;
```

## My additional info

The same problem happens on TYPO3 7.6.x and latest version of direct_mail. The easier way to debug this is to use the page parameter type=99 but I guess the extension is not using the new way TYPO3 handles file references.

Thanks in advance,
  Julian

**Comment by christophlehmann** [comment]
Try 

```
    /**
     * Get images from image field and store this images to $images_arr
     *
     * @param array $imagesArray The image array
     *
     * @return	void
     */
    public function getImagesStandard(array &$imagesArray)
    {
		$fileRepository = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Resource\FileRepository::class);
		$fileObjects = $fileRepository->findByRelation('tt_content', 'image', $this->cObj->data['uid']);
		foreach ($fileObjects as $fileObject) {
			$imagesArray[] = $this->siteUrl . $fileObject->getPublicUrl();
		}
    }
```

**Comment by kartolo** [comment]
see #40 
@christophlehmann will you put your code in a PR, so I can merge it? Thanks

**Comment by rsternec** [comment]
I use the PR-Code from @christophlehmann nearly one year now in production environment and everything works fine. Please merge it.
