### ISSUE TITLE
Make direct_mail 6.0.3 available on packagist

### ISSUE THREAD

**Issue by SomeBdyElse** [kartolo/direct_mail#460]
Hi @kartolo !

After reading https://typo3.org/security/advisory/typo3-ext-sa-2023-011 I just tried to update direct_mail to version 6.0.3. Unfortunately the tag does not seem available on packagist. 

github Tag
https://github.com/kartolo/direct_mail/tree/6.0.3

https://packagist.org/packages/directmailteam/direct-mail#v6.0.3

Please be so kind and publish the 6.0.3 version on packagist as well.

**Comment by kartolo** [comment]
fixed composer.json. [6.0.4](https://packagist.org/packages/directmailteam/direct-mail#6.0.4) is uploaded to packagist
