### ISSUE TITLE
Class "Fetch\Server" not found

### ISSUE THREAD

**Issue by stephangrass** [kartolo/direct_mail#474]
Hi,
after update from TYPO3 9 to 11 and using Direct_Mail 9.5.2, I will get the following error on an non-composer installation:

Core: Exception handler (CLI): Uncaught TYPO3 Exception: Class "Fetch\Server" not found | Error thrown in file /html/typo3/typo3_src-11.5.34/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3216 

Is there a solution?

Thanks 
Stephan

**Comment by fischhase** [comment]
I had the same issue and took the Class File and structure from the older version. It worked for me.

**Comment by kartolo** [comment]
Is it non composer installation? direct_mail needs [tedivm/fetch](https://packagist.org/packages/tedivm/fetch). Until version 7 is tedivm/fetch bundled and was put in `Resources/Private/Php/Fetch`. See https://github.com/kartolo/direct_mail/tree/v7/Resources/Private/Php/Fetch
