### ISSUE TITLE
RequestFactory::request error in v12

### ISSUE THREAD

**Issue by herbertsojnik** [kartolo/direct_mail#486]
If application context is not development, following error occurs on fetching newsletter content:

503 / Oops, an error occurred!
TYPO3\CMS\Core\Http\RequestFactory::request(): Argument #3 ($options) must be of type array, null given, called in .../typo3conf/ext/direct_mail/Classes/Utility/FetchUtility.php on line 47

Problem seems to be, that $context = null; is set in public function getResponse in FetchUtility.php
If I set $context = []; it works for me in development and production context. 

Best regards,
Herbert

**Comment by SSFGizmo** [comment]
merged
