### ISSUE TITLE
Backend modules cannot be accessed by editors in v12

### ISSUE THREAD

**Issue by tillhoerner** [kartolo/direct_mail#488]
It is not possible to grant editors access to the backend modules. This is because in `Configuration/Backend/Modules.php` the access option is set to `'group,user'`, which is not a valid option and should be changed to just `'user'`

**Comment by SSFGizmo** [comment]
* https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.html#access
