### ISSUE TITLE
Creation of dynamic property DirectMailTeam\DirectMail\Scheduler\MailFromDraft::$dmailUid is deprecated

### ISSUE THREAD

**Issue by Zillion01** [kartolo/direct_mail#490]
When starting scheduler task _Create Mail from Draft_

`Creation of dynamic property DirectMailTeam\DirectMail\Scheduler\MailFromDraft::$dmailUid is deprecated in /var/www/html/vendor/directmailteam/direct-mail/Classes/Scheduler/MailFromDraft.php line 90`

12.x

**Comment by SSFGizmo** [comment]
merged
