### ISSUE TITLE
"FoT3\Rdct\Redirects" not found

### ISSUE THREAD

**Issue by weiseger** [kartolo/direct_mail#494]
Hi

I am running a TYPO3 Site with the following settings:

- TYPO3 Version: 11.5.36
- Webserver: Apache
- PHP Version: 8.1.15
- Database: MySQL 8.0.33
- Composer Mode: activated
- OS: Limus 5.15.0-105-generic
- Direct Mail Version: 9.5.2

When I manually send the newsletter by »Invoke Mailer Engine« I receive the error:
Class "FoT3\Rdct\Redirects" not found

Any idea how to fix that? - Thank you for your help

**Comment by jokumer** [comment]
Class FoT3\Rdct\Redirects is part of `[EXT:rdct](https://extensions.typo3.org/extension/rdct)`
As far as I know (not sure), should EXT:directmail depend on it, only if `[EXT:jumpurl](https://extensions.typo3.org/extension/jumpurl)` is loaded.

Fast fix: load EXT:rdct from `friendsoftypo3/rdct`

**Comment by weiseger** [comment]
Awesome! - That´s it!
You made my day..
Thank you

**Comment by jokumer** [comment]
You are welcome.
Please close this issue if it is solved for you.
You may decide to leave further informations on how you did solve your use case - which will help in such situation.
