### ISSUE TITLE
Not compatible with TYPO3 v8 LTS (8.7)

### ISSUE THREAD

**Issue by Patta** [kartolo/direct_mail#53]
composer why-not typo3/cms:8.7.0
directmailteam/direct-mail                     v5.1.1   requires          typo3/cms-core (>=7.6,<8.0)

**Comment by kartolo** [comment]
not tested on 8.7 LTS. will you do some test?

**Comment by Patta** [comment]
i would, but the dependency EXT:jumpurl is also not compatible :/

**Comment by webian** [comment]
Hello @kartolo,
I'm testing in TYPO3 8 LTS and so far I have encountered this problem when browsing the BE modules:
Call to undefined method TYPO3\CMS\Core\Messaging\FlashMessage::render() 

https://wiki.typo3.org/TYPO3.CMS/Releases/7.6/Deprecation#Deprecation:_.2371249_-_Deprecate_render_method_of_FlashMessage_class

**Comment by webian** [comment]
Hello @kartolo 
in this commit https://github.com/kartolo/direct_mail/commit/78134ec0f93f92372a5e2790507aff033d17b994 there are all the changes that I made in my fork to make direct_mail compatible with TYPO3 8 LTS.
It's not optimal but I hope it can help.

**Comment by Patta** [comment]
@webian thanks, works with v8 LTS and jumpurl 7.7.0

**Comment by fischhase** [comment]
Hi webian,

direct mail works ok after your changes. Thank you for that. I got an error, when I send a testmail with empty testmail field. There must be some deprecated code somewhere. Errorpage attached as ZIP (cause of rejection of file type "html" )
[direct_mail-develop.zip](https://github.com/kartolo/direct_mail/files/1004186/direct_mail-develop.zip)

Martin

**Comment by patkar** [comment]
@webian You missed to update the composer.json with the correct constraints ;)

@webian @kartolo Any chances this will become a PR here?

**Comment by kartolo** [comment]
@webian: thanks for fix. could you make a PR? I'll take a look and merge this

**Comment by webian** [comment]
@kartolo I made the PR. Please consider that it's not tested in TYPO3 versions < 8 LTS

**Comment by patkar** [comment]
> that it's not tested in TYPO3 versions < 8 LTS

That should be no problem, as you have raised the minimum requirement to 8.7 :)

**Comment by atomicptr** [comment]
Any news on this issue?

**Comment by kartolo** [comment]
PR is accepted. some things need to be changed to keep compatibility to 7.6 LTS.
