### ISSUE TITLE
Cannot fetch content from password protected https-URLs

### ISSUE THREAD

**Issue by rvock** [kartolo/direct_mail#55]
If you've got a newsletter page on a password-protected https-page, DirectMail fails to add the configured user and password to the URL.

The method [DirectMailUtility::addUserPass](https://github.com/kartolo/direct_mail/blob/v5.1.1/Classes/DirectMailUtility.php#L1275) only checks for http:// and not https://.

A possible fix would look like this:
```php
if ($user && $pass && preg_match('-^(https?://)(.*)$-', $url, $matches)) {
    $url = $matches[1] . $user . ':' . $pass . '@' . $matches[2];
}
```

**Comment by kartolo** [comment]
see #48 if you want to beautify the code, pls create a PR 😄  thanks

**Comment by rvock** [comment]
Thanks :)
