### ISSUE TITLE
Can't create Scheduler Job for Bounce Emails

### ISSUE THREAD

**Issue by ses2013** [kartolo/direct_mail#62]
direct_mail 5.2.0
Typo3 7.6.19

I can't create a new Scheduler Job for Bounced Emails.
Frame stays empty upen saving. Scheduler job not created.

**Comment by kartolo** [comment]
is PHP IMAP extension installed? any PHP error logged?

**Comment by ses2013** [comment]
Yes. As far as I understand the php.info and the server it is running on.
IMAP c-Client Version
2007f
SSL Support
enabled
Kerberos Support

I have to check the php error log though.
enabled

**Comment by ses2013** [comment]
Here is the PHP Error output

Fatal error: Uncaught Error: Class 'Fetch\Server' not found in /home/users/XXX/htdocs/typo3_src-7.6.19/typo3/sysext/core/Classes/Utility/GeneralUtility.php:4547 Stack trace: #0 /home/users/XXX/htdocs/typo3_src-7.6.19/typo3/sysext/core/Classes/Utility/GeneralUtility.php(4519): TYPO3\CMS\Core\Utility\GeneralUtility::instantiateClass('Fetch\\Server', Array) #1 /home/users/XXX/htdocs/www.ctm-festival.de/typo3conf/ext/direct_mail/Classes/Scheduler/AnalyzeBounceMailAdditionalFields.php(116): TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('Fetch\\Server', 'mail.einsnull.d...', 134, 'imap') #2 /home/users/XXX/htdocs/typo3_src-7.6.19/typo3/sysext/scheduler/Classes/Controller/SchedulerModuleController.php(1436): DirectMailTeam\DirectMail\Scheduler\AnalyzeBounceMailAdditionalFields->validateAdditionalFields(Array, Object(TYPO3\CMS\Scheduler\Controller\SchedulerModuleController)) #3 /home/users/XXX/htdocs/typo3_src-7.6.19/typo3/sysext/scheduler/Classes/Controller/SchedulerModuleController.php(217): TYPO3\CMS\Scheduler\Contr in /home/users/XXX/htdocs/typo3_src-7.6.19/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4547

**Comment by kartolo** [comment]
Fetch library is defined in the composer file. did you remove all caches? or have you removed all file caches in typo3temp/Cache/*

**Comment by ses2013** [comment]
Ah Clearing Cache and reinstalling the extension did the trick.
THX

**Comment by ses2013** [comment]
Got warnings though
Warning: Illegal string offset 'rid' in /home/users/XXX/htdocs/XXX/typo3conf/ext/direct_mail/Classes/Scheduler/AnalyzeBounceMail.php on line 223 Warning: Illegal string offset 'rtbl' in /home/users/XXX/htdocs/XXX/typo3conf/ext/direct_mail/Classes/Scheduler/AnalyzeBounceMail.php on line 224 Warning: Illegal string offset 'mid' in /home/users/XXX/htdocs/XXX/typo3conf/ext/direct_mail/Classes/Scheduler/AnalyzeBounceMail.php on line 225

**Comment by kartolo** [comment]
warning is also reported in #80

**Comment by fischhase** [comment]
Hallo kartolo,

I have the same problem. TYPO3 11.5.25 adding the task Analyse Bounce Mail. I deleted typo3temp/* completely, building up the folders via install tool and activated the direct mail extension. It is still happen. I use smtp to send system mails, so I am sure, smtp is working fine. Do you have any idea? 

Thank you

(1/1) Error
Class 'Fetch\Server' not found

in /usr/www/users/domain/typo3/typo3_src-11.5.25/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 3217

            return self::$container->get($className);
        }

        // Create new instance and call constructor with parameters
        $instance = new $finalClassName(...$constructorArguments);
        // Register new singleton instance, but only if it is not a known PSR-11 container service
        if ($instance instanceof SingletonInterface && !(self::$container !== null && self::$container->has($className))) {
            self::$singletonInstances[$finalClassName] = $instance;
        }

at TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('Fetch\\Server', '', 0, 'imap')
in /usr/www/users/domain/webseite/domain.com/typo3conf/ext/direct_mail/Classes/Scheduler/AnalyzeBounceMailAdditionalFields.php line 120

            $mailServer = GeneralUtility::makeInstance(
                \Fetch\Server::class,
                $submittedData['bounceServer'],
                (int)$submittedData['bouncePort'],
                $submittedData['bounceService']
            );

            $mailServer->setAuthentication($submittedData['bounceUser'], $submittedData['bouncePassword']);

at DirectMailTeam\DirectMail\Scheduler\AnalyzeBounceMailAdditionalFields->validateAdditionalFields(array('uid' => 0, 'disable' => '0', 'class' => 'DirectMailTeam\\DirectMail\\Scheduler\\AnalyzeBounceMail', 'type' => '2', 'task_group' => '0', 'start' => 1687431025, 'end' => '', 'frequency' => '', 'multiple' => '0', 'description' => '', 'bounceServer' => '', 'bouncePort' => '', 'bounceUser' => '', 'bouncePassword' => '', 'bounceService' => 'imap', 'bounceProcessed' => '', 'interval' => 0, 'croncmd' => ''), object(TYPO3\CMS\Scheduler\Controller\SchedulerModuleController))
