### ISSUE TITLE
//$message->delete(); ?

### ISSUE THREAD

**Issue by ses2013** [kartolo/direct_mail#64]
Hi there,
why is the "delete"email code deactivated?

  if ($this->processBounceMail($message)) {
                    // set delete
                    //$message->delete();

Cheers
Stefan

**Comment by kartolo** [comment]
you're right. wanted to activated those line before releasing.

**Comment by ses2013** [comment]
Mails set as read but not deleted …

**Comment by kartolo** [comment]
please check
