### ISSUE TITLE
Add user-agent when fetching content of a page

### ISSUE THREAD

**Issue by rsternec** [kartolo/direct_mail#67]
Because of the server security policy in my company it's only allowed to fetch pages when giving some kind of user-agent at the request. For this reason I patched the code for direct_mail locally.

Perhaps it makes sense to take this code into master?

In file **Classes/DirectMailUtility.php** line **1183**:

before:
`$mailContent = GeneralUtility::getURL(self::addUserPass($plainTextUrl, $params));`

after, with user-agent:
`$mailContent = GeneralUtility::getURL(self::addUserPass($plainTextUrl, $params), 0, array('User-Agent: Direct Mail'));`

**Comment by kartolo** [comment]
PR is merged. thank you
