### ISSUE TITLE
Statistics missing information about returned Emails

### ISSUE THREAD

**Issue by ses2013** [kartolo/direct_mail#68]
I can't get any infos about retuned Emails in the statistics.
Always empty. We send only HTML Emails.
Is there any additional Code which needs to be in the HTML newsletter?
![bildschirmfoto 2017-07-06 um 15 50 21](https://user-images.githubusercontent.com/4123330/27914258-e3a2f094-6262-11e7-899b-0f20ecc7ecf1.png)

**Comment by rsternec** [comment]
Did you add bounce mail configuration? Description can be found in the manual:
https://docs.typo3.org/typo3cms/extensions/direct_mail/Configuration/ConfiguringTheAnalysisOfReturnedMails/Index.html

**Comment by ses2013** [comment]
Yes and the emails with wrong adresses get bounced to it.
The Scheduler job works, though it is sometimes marked as running after hours.
The only part I am not sure about is how to use the ###XID### Marker.
Is it needed? And if so where?

**Comment by ses2013** [comment]
Ah I have it as "return_path=###XID###" in the PageTSconfig part mod.web_modules.dmail allready.
Correct this way?

**Comment by kartolo** [comment]
can you please paste header of your newsletter mail?

**Comment by ses2013** [comment]
I changed only the domains to XXX
I noticed that the domain reived from is different then the bounce email domain. possible conflict?

Return-Path: <bounce@XXX.de>
Received: from www.XXX.de ([83.223.82.10]) by mx.kundenserver.de
 (mxeue111 [217.72.192.67]) with ESMTP (Nemesis) id 1MK2Rs-1d80X22lqA-00L9Hu
 for <ses@XXX.de>; Fri, 07 Jul 2017 08:55:26 +0200
Received: from www.XXX.de (localhost [127.0.0.1])
	by www.XXX.de (Postfix) with ESMTP id D6F3B1840075
	for <ses@XXX.de>; Fri,  7 Jul 2017 08:55:24 +0200 (CEST)
Message-ID: <e0e6897edaabb83c5be7b5f285e2a9c0@www.XXX.de>
Date: Fri, 07 Jul 2017 08:55:24 +0200
Subject: Newsletter #162 =?utf-8?Q?=E2=80=93?= CTM 2018
From: CTM Festival <news@XXX.de>
Reply-To: "" <news@XXX.de>
To: <ses@XXX.de>
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="_=_swift_v4_1499410524_4d0c6a78f176bf398f19a1144b2d845e_=_"
X-TYPO3MID: MID194_t10608-0ad1714fd588b6d4ddfa056947602bf5
X-Priority: 3 (Normal)
X-Mailer: TYPO3
Organization: CTM
Envelope-To: <ses@XXX.de>

**Comment by wiggum70** [comment]
I had the same problem and found that the header-attachements from the returnmail have not been read. I changed line 512 of Message.php from the Fetch-src to 
> || (isset($structure->subtype) && stripos($structure->subtype, 'rfc822') !== false)

![bildschirmfoto 2017-07-20 um 10 19 07](https://user-images.githubusercontent.com/30312616/28408324-636a98c0-6d37-11e7-960d-126092fc7f9b.png)

Perhaps the use of the latest Fetch-library also helps.

![bildschirmfoto 2017-07-20 um 10 25 48](https://user-images.githubusercontent.com/30312616/28408346-744ae0be-6d37-11e7-9d55-9b9857469f55.png)

**Comment by kartolo** [comment]
@ses2013 return_path should be ok, if you put `noreply@domain.tld` and it's your bounce account. If you have a catchall address, you can put `noreply+###XID###@domain.tld`. then while sending the newsletter it would become `noreply+MAIL_ID@domain.tld`

could you check in the table sys_dmail_maillog for response_type=-127? it's your bounces records.

**Comment by kartolo** [comment]
@wiggum70 in the latest library it's still using the == comparison. Perhaps some exotic mail server out there sending `rfc822-headers` type. I guess I'll fix this directly in the library embedded in direct_mail
