### ISSUE TITLE
TYPO3 7.6.4 + fluid 7.6.0 + fluid_styled_content 7.6.0

### ISSUE THREAD

**Issue by erthi16** [kartolo/direct_mail#7]
I am testing the installation of Direct Mail and I have only succeded in sending the "quickmail" and the "external pages" (other direct mail on TYPO3 6.2.19).

The "internal pages" option always return that there are no HTML or TEXT content.  

My site is hosted on a temporary serveur with no domain name... just an IP adress with my user name account.  To make life easier for my clients, I've changed their host file (and mine) by adding a temporary domain... it is not possible to change directly on the hosting server.

If I understand correctly, the fetching of the internal page cannot succeed because the script cannot resolve the name VS IP of my temporary site? As the site will be hosted under a real domain name only when finished, I cannot program the newsletter functionnality!

Can you point me to some possible solutions?

Is Direct Mail compatible with fluid and fluid_styled_content?

A million thanks to you!

Eric Thibault

**Comment by kartolo** [comment]
Plain text transformation is not tested on fluid_styled_content.
direct_mail creates a link to the newsletter page (PID) and domain, from which the BE is called or first sys_domain on the root. direct_mail gets the page using GeneralUtility::getURL.
Please check:
- is curl active in install tool
- can your server calls itself? per ssh please fetch the page per wget or curl.

**Comment by erthi16** [comment]
Thanks for your answer!

CURL is activated but I have no domain name in our DNS server yet... It will only be given on delivery day!!! I will try to get one before that or test on a different serveur with the same configuration.

Eric Thibault
