### ISSUE TITLE
Markers used in direct_mail template with fluid_styled_content templates

### ISSUE THREAD

**Issue by angeloprevitali** [kartolo/direct_mail#97]
Hello

we would like to use the EXT:direct_mail v. 5.2.2 with the version of TYPO3 CMS version 8LTS with fluid_styled_content, without installing css_styled_content. The markers get not replaced when sending the newsletter. 

Is there a way to replace the existing ### Markers ### together with fluid_styled_content?

Thanks for help us out.

Regards,
Angelo Previtali

**Comment by Hobokens** [comment]
Hi Angelo Previtali,
did you find a solution for the described problem? I built my own fluid template for the HTML view sucessfully but the mark for plain text isn't filled in.

Regards
Hobokens

**Comment by alandolsi** [comment]
I'm interessted to kwnow the solution too

**Comment by angeloprevitali** [comment]
I found the solution for the described problem: 

In a TYPO3 CMS verson 8.7 create a new BE template (for FLUID) and add the HTML Code from the direct_mail template file into this FLUID template. Now if you add this template for creating new newsletters add this template in the BE of the page properties and send the newsletter as usual. All old ### MARKERS ### gets rendered AND also all FLUID code which is in the template gets rendered as it should.
