### ISSUE TITLE
TYPO3 8: Error due to breaking API Change

### ISSUE THREAD

**Issue by christianriesche** [kartolo/direct_mail#99]
> Fatal error: Uncaught Error: Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::exec_mm_query_uidList() in C:\Users\me\project\htdocs\typo3conf\ext\direct_mail\Classes\Container.php:74 

```
===============================================================================
Breaking: #75711 - Removed DB-related methods and TCA-related options from cObj
===============================================================================

See :issue:`75711`

Description
===========

The following methods have been removed from `ContentObjectRenderer` without substitution:

* DBgetDelete()
* DBgetUpdate()
* DBgetInsert()
* DBmayFEUserEdit()
* DBmayFEUserEditSelect()
* exec_mm_query()
* exec_mm_query_uidList()
```

**Comment by frankfuX** [comment]
possible replacement could be

                    $res = $GLOBALS['TYPO3_DB']->exec_SELECTquery(
			$select,
			$mmTable. ',' . $foreignTable,
			$mmTable . '.uid_local IN (' . $localTableUidList. ')' .
				' AND ' . $foreignTable. '.uid=' . $mmTable. '.uid_foreign' .
				$whereClause, 
			'',
			$orderBy,
			''
                    );

**Comment by kartolo** [comment]
Doctrine DBAL rewrite is WIP in #133. So I close this
